### ISSUE TITLE
Allow exporting object fields as read-only without requiring custom accessors

### ISSUE THREAD

**Issue by dawkot** [nim-lang/RFCs#100]

**Comment by Quelklef** [comment]
If anyone is interested, I've (by coincidence) made a package that does this [here](https://github.com/quelklef/nim-finals).

It has a number of caveats, unfortunately, which I think are unavoidable. If this behavior gets in high demand, it looks like it should be added to the core language.

**Comment by bluenote10** [comment]
I'm trying to compare the two ideas here. My understanding is that the read/write patterns would be the following in terms of internal (same module) and external (other modules) access.

**Idea 1**

| definition | internal | external |
|------------|:--------:|:--------:|
| field*     |   r + w  |   r + w  |
| field-     |   r + w  |     r    |
| field      |   r + w  |     -    |

**Idea 2**

Sorted from least restrictive to most restrictive:

| definition               | internal | external |
|--------------------------|:--------:|:--------:|
| field*: int              |   r + w  |   r + w  |
| field*: int {.readonly.} |     r    |     r    |
| field: int               |   r + w  |     -    |
| field: int {.readonly.}  |     r    |     -    |

What I like about the second idea:
- Accessibility is consistent across internal/external, and the export symbol decided whether the outside gets the same as the own module (=> less worries when refactoring modules).
- It adds the feature of fully immutable fields -- something I would highly welcome.

What the second idea misses is the `r + w / r` pattern though. On the other hand, this is the easiest one to achieve with the current language via an inline getter proc or even a custom pragma `field: int {.publicGetter.}` that auto-generates the getter.

Personally I see much more value in expressing the invariant of a class compared to more convenient public getters for mutable fields, especially since it looks like same-module-immutable-fields are impossible for now.

Name-wise I would slightly prefer `-` over `+`, and @Quelklef 's `{.final.}` over `{.readonly.}`.

**Comment by shumy-tools** [comment]
@bluenote10 I believe idea 1 is the one to go. What really matters is to define and follow a contract, from a point of view of an external use. Readonly is very useful when the owner of the module wants to maintain the mutability under control, such as controlling the size of a variable sequence. And I believe such feature should be built in.

Idea 2 doesn't follow the readonly contract:

1) ```field: int {.readonly.}``` and ```field*: int {.readonly.}``` is not readonly. This is immutability, a different beast and useful in multi thread context. Immutability is completely broken when ref fields enter the scope, and this won't help to solve it. Immutability should be discussed carefully and specified in a different context.

2) The most useful feature of readonly is missing, the "field-".

**Comment by g5becks** [comment]
any updates on this?

**Comment by timotheecour** [comment]
I don't see why we need a new language feature for that, it'd add complexity to the language and not be flexible enough; a library solution should be enough, unless I'm missing something.

```nim
import std/macros # defines `access` pragma macro
type Foo {.access.} = object
  a2 {.readonly.}: int
  a3 {.writeonly.}: int
  a4: int
  a5*: int

# and just expose a ctor for outside clients, eg:
proc initFoo*(a2, a3, a4, a5) : Foo = ...
```

**Comment by g5becks** [comment]
@timotheecour I was actually looking at the [solution](https://github.com/quelklef/nim-finals) provided above. Looks like it works fine enough, but for my exact use case, I need it to work with object hierachies. I'm not 100% sure what the workaround is for this without language level support.

**Comment by timotheecour** [comment]
> I need it to work with object hierachies

what's the problem?

```nim
# fun.nim
type Foo* = object of RootRef
  f1: int
type Goo* = object of Foo
  g1: int
proc initFoo*(f1: int): Foo = Foo(f1: f1)
proc initGoo*(f1, g1: int): Goo = Goo(f1: f1, g1: g1)
proc f1*(a: Foo): auto {.inline.} = a.f1

# main.nim
import ./fun
let a = initFoo(f1 = 3)
echo a.f1
# a.f1 = 5 # CT error as intended
let b = initGoo(f1=3, g1=4)
echo b.f1 # works
```

**Comment by g5becks** [comment]
I was speaking about the library that I linked to which implemented this via pragma, which [doesn't allow this](https://github.com/quelklef/nim-finals#contructors-and-object-hierarchies)

> what's the problem?

Technically none, on a subjective level - I find it more intuitive / user friendly to have a modifier like readonly in C# / Typescript, or final in Java and friends as opposed to having to write a seperate getter.

**Comment by timotheecour** [comment]
> as opposed to having to write a seperate getter.

you don't have to write it, all that's needed is:
```nim
import std/macros # defines `access` pragma macro
type Foo {.access.} = object
  a2 {.readonly.}: int
  a3 {.writeonly.}: int
  a4: int
  a5*: int
```

I don't see a need for a language extension here, unless you can show where this fails

**Comment by g5becks** [comment]
@timotheecour 

I tried the solution above today, I couldn't find anything about it in the docs, and when I ran it I got thefollowing error.

> Error: invalid pragma: access

Could you link to the docs on this pragma?

**Comment by timotheecour** [comment]
that's yet to be written, my point is it's possible

**Comment by Varriount** [comment]
We need a decent way for type definitions to generate procedures that doesn't involve weird workarounds due to https://github.com/nim-lang/Nim/issues/13375
