### ISSUE TITLE
Transferring issues from nim to here

### ISSUE THREAD

**Issue by dom96** [nim-lang/RFCs#141]
What is the criteria for moving feature requests here?

I ask because I really dislike having an issue moved without my consent. It really ruins my ability to search for it and makes me mistrust my sanity.

Can we please stop doing this, unless the issue creator explicitly states "RFC" in the title?

**Comment by Araq** [comment]
There is less difference between a "feature request" and an RFC than between a feature request and a bug.

**Comment by narimiran** [comment]
> It really ruins my ability to search for it and makes me mistrust my sanity.

1. Look at the top bar. There are: "Pull requests", "Issues", "Marketplace", "Explore".
2. Click on "Issues".
3. Find your issue you're looking for.
4. Keep your sanity.

> I ask because I really dislike having an issue moved without my consent. 

Ok, next time open your issue (which was not really an issue, but more of ["a call for a discussion"](https://github.com/nim-lang/RFCs/issues/140)) here (look at the description: "A repository for your Nim proposals." - this also answers the question about the criteria for moving stuff here) and it won't be moved ;)

> Can we please stop doing this, unless the issue creator explicitly states "RFC" in the title?

Why does the issue creator deliberately (he acknowledged himself in the title that he's opening an RFC) give us more work to do, instead of opening it here in the first place? ;)

-----

Why do we have this repo if anybody can just say "I opened my issue in the wrong place and I demand to stay there for eternity"? It is not fair to the others who 'play by the rule' and open their RFCs/proposals/discussions here.

**Comment by dom96** [comment]
> 1. Look at the top bar. There are: "Pull requests", "Issues", "Marketplace", "Explore".
> 2. [...]

Am I missing something? My point is that I looked for it in the Nim repo, if I don't get a notification that my issue was moved and am looking quickly for an issue to reference it to someone it's really not fair to assume that I will be able to connect the dots and look in this repo.

> Ok, next time open your issue (which was not really an issue, but more of "a call for a discussion")

What if I don't want to? What purpose does this repo really serve? If this repo requires us to submit formal RFCs then I can get behind it, but if it's just a repo for "Nim features" then you should probably move all [140 of these "Features" in the Nim repo](https://github.com/nim-lang/Nim/issues?q=is%3Aopen+is%3Aissue+label%3AFeature) but that would be a little silly wouldn't it?

So why move my issue here? I disagree btw, it's not a "call for discussion", it's a feature. It's not even a language feature, just a feature request for the docgen.

**Comment by krux02** [comment]
I am closing this, as this is not an RFC but a question. You can ask your qestions any time on IRC, I am online there quite often. This repository mainly serves us to manage the over 1000 issues from Nim.
