### ISSUE TITLE
Use a keyword different from `distinct` for `bind many` behaviour

### ISSUE THREAD

**Issue by mratsim** [nim-lang/RFCs#153]
## Context

See https://forum.nim-lang.org/t/5008#31415.

## Proposal

Both `distinct` types and bind once/bind many are advanced concepts that are using the same `distinct` keyword.

Due to this when `distinct` keyword is needed for bind many behaviour at the type section level, it requires complex gymnastics until something works. I suggest that the bind once/bind many is controlled by a different keyword to improve discoverability and ergonomics.

### Goal, Make this compile:

```Nim
type
    AbstractType = int or string
    TestType*[T : AbstractType, Y : AbstractType] = object
        a : T
        b : Y

proc newTestType[T : AbstractType, Y : AbstractType](a : T, b : Y) : TestType[T, Y] =
    return TestType[T, Y](a : a, b : b)

proc print_test_type(t : TestType) =
    echo t.a
    echo t.b

let
    t1 = newTestType(1, 2)
    t2 = newTestType("string", "here")
    t3 = newTestType(10, "mixed")

echo typedesc(t1)
print_test_type(t1)

echo typedesc(t2)
print_test_type(t2)

echo typedesc(t3)
print_test_type(t3)
```

### In-depth explanation

Welcome to Nim.

You are actually touching an advanced part of the Nim type system, the ``bind once`` versus ``bind many`` part.

#### bind once vs bind many

Let's go through that with an example.

```Nim
proc foo1(x, y: SomeInteger) =
  echo "Ran foo"

proc foo2(x: SomeInteger, y: SomeInteger) =
  echo "Ran foo"

proc bar[T, U: SomeInteger](x: T, y: U) =
  echo "Ran bar"

proc baz(x, y: distinct SomeInteger) =
  echo "Ran bar"

let a = int32 10
let b = int64 20

block: # fails
  foo1(a, b)

block: # fails
  foo2(a, b)

block: # works
  bar(a, b)

block: # works
  baz(a, b)
```

In the first case ``foo1``, from the signature it is intuitive that ``x`` and ``y`` should be of the same type.

The second case ``foo2`` is equivalent to ``foo1``, for generic instantiation, once ``SomeInteger`` has been inferred from the first parameter, it is applied everywhere else. It is called ``bind once``.
The main benefit is that both definition are interchangeable, and it seems to be a good default.

There are 2 ways to ask the compiler to not bind once.

Option 1 via indirection: in the ``bar`` function, ``x`` of type ``T`` which is instantiated to int32, and ``y`` of type ``U`` which is instantiated to int64. The ``[T, U: SomeInteger]`` declaration only restrict T and U to be of SomeInteger but never instantiates ``SomeInteger`` so it's not bind to any concrete type like in the 2 previous examples.

Option 2 via explicitly asking ``bind many`` behavior: in the ``baz`` function, the ``distinct`` keyword tells the compiler to not lock the inference of ``SomeInteger`` to the type of ``x``.

#### The tricky part 1: distinct solution

Hopefully the examples are simple enough and you managed to follow me until here.
The key part to remember is that ``distinct`` tells the compiler to not ``bind once``.

You might think, oh I just need to use distinct for my types then.

```Nim
type
    AbstractType = int or string
    TestType*[T, Y : distinct AbstractType] = object
```

Unfortunately, ``distinct`` has a completely different meaning in a type section.

#### ``distinct`` types

Distinct types are well covered in the manual. It allows you to create units (for example physics units like Meter and Mile or currency like Dollar and Euro) and prevent you from mixing them at the type system level.

Example
```Nim
type
  Dollar = distinct int
  Euro = distinct int

# Let's borrow procedures from the base ``int`` type
proc `+`(x, y: Dollar): Dollar {.borrow.}
proc `+`(x, y: Euro): Euro {.borrow.}

# And overload the print to add the unit
proc `$`(x: Dollar): string =
  $int(x) & " dollars"

proc `$`(x: Euro): string =
  $int(x) & " euro"

let a = 10.Dollar
let b = 3.Dollar

let c = 5.Euro
let d = 1.Euro


echo a+b # Prints 13 dollars
echo c+d # Prints 6 euros

# Compile-time error "Type mismatch"
# echo a+c
```

#### The tricky part 2: indirection solution

Since ``distinct`` doesn't work in a type section. You might think, well I can use the ``bar`` solution, bind ``T`` and ``U`` to different types.

```Nim
type
    AbstractType = int or string
    TestType*[T: AbstractType; Y: AbstractType] = object
        a : T
        b : Y

proc newTestType[T, Y: AbstractType](a: T, b: Y) : TestType[T, Y] =
    return TestType[T, Y](a : a, b : b)

proc print_test_type(t : TestType) =
    echo t.a
    echo t.b

let
    t1 = newTestType(1, 2)
    t2 = newTestType("string", "here")
    t3 = newTestType(10, "mixed")

echo typedesc(t1)
print_test_type(t1)

echo typedesc(t2)
print_test_type(t2)

echo typedesc(t3)
print_test_type(t3)
```

Well unfortunately it doesn't work, within a type section, all the generic T, Y types are ``bind once``.

#### The solution

@thenjip nailed it, you need to shake the typesystem a bit until you "bind many indirections" directly at the type section level instead of the proc level:

```Nim
type
    AbstractType = int or string
    TestType*[T : distinct AbstractType | AbstractType; Y : distinct AbstractType | AbstractType] = object
        a : T
        b : Y

proc newTestType[T, Y](a: T, b: Y) : TestType[T, Y] =
    return TestType[T, Y](a : a, b : b)

proc print_test_type(t : TestType) =
    echo t.a
    echo t.b

let
    t1 = newTestType(1, 2)
    t2 = newTestType("string", "here")
    t3 = newTestType(10, "mixed")

echo typedesc(t1)
print_test_type(t1)

echo typedesc(t2)
print_test_type(t2)

echo typedesc(t3)
print_test_type(t3)
```

#### Language design

For future improvement of the language, I think the ``distinct`` keyword to create unit types and the ``distinct`` keyword for the ``bind many`` type inference should be separated to improve language ergonomics. We could use ``mixed`` instead for the ``bind many``

```Nim
proc baz(x, y: mixed SomeInteger) =
  echo "Ran bar"
```

## My take

Explaining both concepts separately would be much easier, but right now when needing the `bind many` rule in a type section, very intricate knowledge of type classes, distinct types and generic binding rule is required.

Having `distinct` do only one thing (distinct type) and a new keyword like `mixed` doing only one thing would be much better.

**Comment by zah** [comment]
Historically, the `distinct` keyword was reused, because in a language with keywords it makes sense to keep them at a minimum. Nowadays, the grammar of Nim has improved significantly and it's possible to define both `distinct` and `mixed` as overloaded magics that take a typedesc parameter instead. 

Reducing the number of keywords is a worthy cause, because once a keyword becomes a function, it can play with other abstractions in the type systems. It can be passed as an argument to a template, it can be sometimes lifted to a run-time functions and so on.

**Comment by zah** [comment]
`mixed` has some connotations with `mixin` though. Other possible magic names are `bindMany`, `unbound`,  `nonbinding`, `diverse`, `hetero`

**Comment by krux02** [comment]
I would like to add my two cents here as well. In my opinion the bind many feature should be marked as deprecated and in the long run removed from the language. 

The costs of this feature are complexity in the compiler, the specification, and last but not least in learning the Language of Nim. On the benefit side, I don't see this feature to have any benefit at all. 
It creates complexity in the compiler and it creates complexity for the reader to understand the code. 

In this code snippet I would recommend to use the ``bar`` variation of the proc all the time. On the plus side it also makes clear to the readers that this procedure has generic parameters.

```nim
proc bar[T, U: SomeInteger](x: T, y: U) =
  echo "Ran bar"

proc baz(x, y: distinct SomeInteger) =
  echo "Ran bar"
```

I would even go so far to recommend in Nim style guides to always use explicit generic parameters for generic procedures, as they are more syntactically transparent in what they are: a generic procedures.

For the code snippet that does not compile, that is just a bug. I think it is related to ``typedesc``. I think I encountered it as well. I think it should simply be fixed. But until that has been done, there is a workaround: use the result variable that is already correctly instantiated

```nim
proc newTestType[T : AbstractType, Y : AbstractType](a : T, b : Y) : TestType[T, Y] =
  result.a = a
  result.b = b
```

**Comment by zah** [comment]
I don't think there is a particularly good reason for the generic procs to stand out. The implicit generic style often produce shorter code and shorter code is easier to read for me. 

With implicit generics, you are also baking less assumptions into the code. If I'm writing a matrix library and my procs look like this:

```nim
proc `*`(a, b: Matrix) = ...
```

... I can add additional generic parameters to the generic `Matrix` type without changing any of the existing definitions. With the explicit generics style, writing all the signatures would be more bothersome and modifying the type will be more painful.

**Comment by krux02** [comment]
As I have written a matrix library myself (I am the maintainer of [nim-glm](https://github.com/stavenko/nim-glm). I have an opinion on this as well, and in should one could say that I simply disagree.

> I don't think there is a particularly good reason for the generic procs to stand out.

There is a good reason why generic procs should stand out. One of them is for me, their semantic check is incomplete on generic procedures, so they are harder to get right. For non generic procedures you just know that they won't cause a type check errors later on. Also for the compilation it makes a difference. Generic procedures are instantiated lazily,  this might have an impact on compile times. Simply speaking generic procedures are more complex, and more complex things justify in my opinion a more complex syntax.

> The implicit generic style often produces shorter code [...]

I agree the implicit generic style is shorter. But I don't agree that shorter at all costs is a good thing.

>  and shorter code is easier to read for me.

Yes for _you_, but you defined all those Generic types. You know that when you write ``proc foo(a, b: Matrix) = ...`` that it is generic, because ``Matrix`` is your type definition. For people who are just reading the code and didn't take a look at the implementation of ``Matrix`` yet, this is not the case.

Apart from that I don't think that the shortness is really that big of an argument here. To my experience the difference in code size is only visible in tiny examples. In bigger projects like in nim_glm, I don't think I could save a single line of source code if I would use the implicit style.

> Thus, at Status, we recommend the use of the implicit style whenever possible.

It is very good for you that you convinced everybody at status to program in your personal preference of style. And don't worry, I won't remove this style from the language, you can continue to do so. I think it has been too long in the language to get rid of it now. But I am not a fan of it and I will recommend people to not use it. It is just the bind many types that I would really like to go in the long run, because here not even the shortness argument works, it is pure code obfuscation.

> I can add additional generic parameters to the generic Matrix type without changing any of the existing definitions. 

There were already bugs in the compiler caused by these implicit generic parameters. I can't find the issue right now, but It was alse related to ``typedesc``, and I have a very special relationship with ``typedesc``.

> With the explicit generics style, writing all the signatures would be more bothersome and modifying the type will be more painful.

True. But I don't see this as a problem, because I don't see myself constantly adding generic parameters to types. I even think optimizing the syntax for adding and removing generic parameters to types easily is counterproductive, because you should not do that. But that last sentence is just my personal opinion.

**Comment by Araq** [comment]
Having written the spec for it recently, I don't see why "distinct" typeclasses in implicit generics are a thing. When it really comes up, write the type parameters explicitly. Simple, works with today's compiler.
