### ISSUE TITLE
Wider range for type inference

### ISSUE THREAD

**Issue by bifunctor** [nim-lang/RFCs#155]
Could a wider range for type inference be added? For example, making `types` can not be auto-typed; An example:

```nim
type Animal = ref object of RootObj
  age: auto
  name: auto

var my_animal = Animal(name: "Tom", age: 3)
```
This code will give an error. A slightly better (but not a desired) alternative is to use generics; An example:

```nim
type Animal[T, U] = ref object of RootObj
  age: T
  name: U

var my_animal = Animal[string, int](name: "Tom", age: 3)
```
This code does not raise an error. Though this method is better, it still lacks the element of type inference.

**Comment by bluenote10** [comment]
This probably cannot work, because what happens if you have

```nim
var my_animal_a = Animal(name: "Tom", age: 3)
var my_animal_b = Animal(name: 3, age: "Tom")
```

or if you never instantiate `Animal`? If you want it to be generic, you have to use generics.

Maybe your motivation is to avoid having to repeat fields types when you write a type **and** an accompanying constructor function? I have a concise solution for that in my [oop_utils](https://github.com/bluenote10/oop_utils) library:

```nim
import oop_utils/standard_class

class(Animal):
  ctor proc(name: string, age: int) =
    self: # the self block basically defines the fields of the type
      name
      age

let animal = Animal.init("Tom", 3)
```

Note that the field types occur only once.
