### ISSUE TITLE
Const import from C headers

### ISSUE THREAD

**Issue by mratsim** [nim-lang/RFCs#157]
### Summary

C headers often defines constant `#define 123`. Currently if we want to work directly with those we need to use a var for `importc`.

Examples:

- `fenv`: https://forum.nim-lang.org/t/3762
- Real-time clock: https://github.com/nim-lang/Nim/issues/11853
- mmap: https://github.com/nim-lang/Nim/blob/7ef268274f387530b85f5a9f704e0eda5a7aa022/lib/system/osalloc.nim#L199-L216
```Nim
elif defined(posix):
  const
    PROT_READ  = 1             # page can be read
    PROT_WRITE = 2             # page can be written

  when defined(macosx) or defined(bsd):
    const MAP_ANONYMOUS = 0x1000
    const MAP_PRIVATE = 0x02        # Changes are private
  elif defined(solaris):
    const MAP_ANONYMOUS = 0x100
    const MAP_PRIVATE = 0x02        # Changes are private
  elif defined(linux) and defined(amd64):
    # actually, any architecture using asm-generic, but being conservative here,
    # some arches like mips and alpha use different values
    const MAP_ANONYMOUS = 0x20
    const MAP_PRIVATE = 0x02        # Changes are private
  elif defined(haiku):
    const MAP_ANONYMOUS = 0x08
    const MAP_PRIVATE = 0x02
  else:
    var
      MAP_ANONYMOUS {.importc: "MAP_ANONYMOUS", header: "<sys/mman.h>".}: cint
      MAP_PRIVATE {.importc: "MAP_PRIVATE", header: "<sys/mman.h>".}: cint
```
- `cpuset`: https://github.com/nim-lang/Nim/blob/bb949a75db490c9bccae975855310ee2de0b4b28/lib/system/threadlocalstorage.nim#L180-L182
```Nim
  type CpuSet {.importc: "cpu_set_t", header: schedh.} = object
     when defined(linux) and defined(amd64):
       abi: array[1024 div (8 * sizeof(culong)), culong]
```
  The 1024 is correct on linux but should be 256 on FreeBSD and who knows what on Solaris.

### Description

Allow importc into Nim constants. There is no need to write a full C preprocessor, we can just keep the C symbol around and directly use it in the generated C code.

This has the following limitations:
- constant represented by a symbol in the VM instead of value. I think this is already somewhat the case for objects but I'm not sure.
- no addition / sizeof / etc in the VM: that's already the case today with C FFI in general.

It has the benefits of being able to write portable code without having to check platform specific defines when Linux, BSD, Haiku, Solaris, MacOS(X), ... don't agree on them, for example `mmap` or `cpuset` sizes

### Alternatives
1. Keeping the current situation, which led to code like this:
```Nim
# Linux parameters
const CpuSetSize* = 1024
type CpuMaskType = culong

# On BSD CPU_SETSIZE is 256
# On Solaris ?
# On MacOSX?
# On MacOS?
# On Genode?
# On Haiku ...

when defined(debug):
  var Debug_CPU_SETSIZE {.importc: "CPU_SETSIZE", header: "<sched.h>".}: int
  assert Debug_CPU_SETSIZE == CpuSetSize, "Platform is misconfigured"
type
  CpuSet* {.byref, importc: "cpu_set_t", header: "<sched.h>".} = object
    ## A set of CPUs for affinity manipulation.
    ## Implemented as an opaque bitset manipulated by C macros.
    # Always passed by hidden pointer
    when defined(linux) and defined(amd64):
      abi: array[CpuSetSize div (8 * sizeof(CpuMaskType)), CpuMaskType]
```

2. Compile-time FFI: https://github.com/nim-lang/Nim/pull/10150

3. Run part of c2nim parsing to directly get the value of const #define.
    This however requires Nim to resolve paths like <sched.h> that have a lot of includes
    behind the scene.

**Comment by krux02** [comment]
As I am writing many wrapper libraries on my own, I encountered the problem that an integer type may be defined differently for different platforms. For example ``int_least16_t``. How do I wrap code that uses types like this? The size is not defined, it is not known to Nim.  ``type least16 {.importc: "int_least16_t".} = int`` does work, but it sets the size for the Nim compiler incorrectly. I am not 100% sure if this problem should be tackled in the same RFC, right now I think it should.

I problem that I see in your proposal is, that you want to import a const from C. I don't think we can import them as ``const``, since const is defined to be known at Nim compile time. We don't know any constants from C at Nim compile time, because the compilation of Nim and C is strictly separated.

**Comment by arnetheduck** [comment]
See https://github.com/nim-lang/Nim/pull/5698 - this would involve teasing exact definitions from each libc, potentially with a "fallback" generic ANSI/posix C that uses `var` instead. It would involve improving the nim platform detection as well, as is, it can't really express the differences clearly enough (musl vs uclibc vs glibc for example)

The alternative is that the language gains better interop support to deal with this properly - a const/var mixed thing designed specifically for interop.

And finally, nim does not really have an ABI - creating the language primitives to express one would allow dealing with `int_least_16` and the like by selecting one. 

it will always be limiting not to have exact type at the nim level (because it prevents lots of compile-time techniques) - and more onerous to wrap.

**Comment by timotheecour** [comment]
@mratsim this is what I've been using: 
* step 1: compile nim with `-d:nimHasLibFFI` (see https://github.com/nim-lang/Nim/pull/10150)
* step 2: `nim c --experimental:compiletimeFFI main.nim`
* step 3: there is no step 3. just need to lobby so we can re-enable testing for CTFFI in testament to make sure it keeps working (cf https://github.com/nim-lang/Nim/pull/11991 )

```nim
when defined timn_with_dynlib:
  {.emit:"""
  #include <unistd.h>
  NIM_EXTERNC
  int wrap_STDERR_FILENO(){ return STDERR_FILENO;}
  // etc: define each symbol you want to export; maybe group in a single C struct
  """.}
else:
  import std/[strformat,os]
  const mylib = "/tmp/libz01.dylib"
  proc precompile() =
    const file = currentSourcePath()
    let cmd = fmt"""{getCurrentCompilerExe()} c -o:{mylib} --app:lib -d:timn_with_dynlib {file}"""
    # proper implementation would cache result
    echo (cmd: cmd)
    let (output, exitCode) = gorgeEx(cmd)
    if exitCode != 0:
      doAssert false, output
  static: precompile()

  {.push importc, dynlib: mylib.}
  proc wrap_STDERR_FILENO(): cint
  # etc
  {.pop.}

  const STDERR_FILENO* = wrap_STDERR_FILENO()
  static: doAssert STDERR_FILENO == 2
```

My full implementation adds macro sugar to make it easier to use but this should give you the idea.

I'm using CTFFI extensively since
