### ISSUE TITLE
outplace and chaining

### ISSUE THREAD

**Issue by Araq** [nim-lang/RFCs#192]
There have been a couple of competing designs in order to add ``outplace`` and ``chaining`` to Nim. Here is a new one that tries to be convenient to use, simple to implement and without gotchas. Names have been chosen instead of operators for two reasons:

* How they interact with the "dot notation" is obvious.
* Many people prefer words over Perl-like custom operators. 

# outplace / dup

The current ``outplace`` should be renamed to ``dup`` focussing on the "works on a duplicate/copy" aspect. ``dup`` looks like the following:

```nim

macro dup*[T](x: T; calls: untyped): T = discard "implementation not part of the spec"

# examples
var a = @[1, 2, 3, 4, 5, 6, 7, 8, 9]
doAssert a.dup(sort()) == sorted(a)

var aCopy = a
aCopy.insert(10)

doAssert a.dup(insert(10).sort()) == sorted(aCopy)
doAssert a.dup(insert(_, 10).sort()) == sorted(aCopy)
```

As can be seen in the examples, the 2nd argument to ``dup`` is a list of "dot call expressions". The call expression can contain ``_``, if so the ``_`` is replaced by the copy that ``dup`` introduces. Otherwise the copy is passed as the first argument to the call.

# chain / operateOn / on / use

The ``operateOn`` macro should be renamed to ``use``. It looks like this:

```nim

macro use*[T](x: T; calls: untyped): void = discard "implementation not part of the spec"

var w: Window
w.use(setColor(green).setPosition(10, 20).setVisible(true))
```

The same rules apply as for ``dup``, the 2nd argument is a list of dot call expressions with optional ``_`` markers. Notice that ``dup`` returns an expression of type ``T`` and that ``use`` returns an expression of type ``void``.

# Block syntax

Both operations also work with a "block syntax", the 2nd argument then is a block of statements that is transformed.

```nim

use w:
  setColor(green)
  setPosition(1, 2)
  setVisible(true)

@[1, 2, 3, 4, 5].dup:
  insert 10
  sort()
  filterByIt it != 4
```

The block syntax does not support control flow, ``if`` etc are not allowed, only a flat list of call expressions and for every call the first argument is injected. The macros are deliberately not smart.

# Alternatives to consider

- Use ``with`` instead of ``use`` since it's now very close to Pascal's ``with`` statement (only better, because no guesswork is involved).
- Use ``,`` for the non-block chaining syntax as it avoids ambiguities and feels more natural:

```nim

doAssert a.dup(insert(10), sort()) == sorted(aCopy)

```

This has the benefit that then simple calls can be written without the ``()``: 

```nim

doAssert a.dup(algorithm.sort) == sorted(aCopy)

```

**Comment by andreaferretti** [comment]
I especially like the block syntax!

**Comment by Varriount** [comment]
Hm, interesting. While I'm still mulling the RFC over, one thing that does occur to me is that the block form of `on` somewhat replicates the implicit `this/self` argument mechanism that other languages use as part of their object-oriented programming features.

**Comment by dom96** [comment]
As someone that disliked `outplace` a lot initially (especially with the operator that was initially being proposed), let me say that **I love the ``dup`` name**.

Regarding ``on`` though, I think ``chain`` would be much better: ``on`` is far too short and ambiguous, ``chain`` captures the purpose very well and is much easier to search for.

**Comment by exelotl** [comment]
Question, does `on` also allow statements that don't operate on the target?
e.g.
```nim
on w:
  setPosition(1, 2)
  echo "hello"
  if uiHidden:
    return
  setVisible(true)
```
This would be preferable to me, as a worthy replacement for the `this` pragma. But either way I like these additions a lot!

**Comment by hlaaftana** [comment]
Another name for `on` could be `doto` or `doTo`, as in clojure

**Comment by Araq** [comment]
> Question, does on also allow statements that don't operate on the target?

No. In fact, the block has to consist of only calls and control flow is not allowed.

> Another name for on could be doto or doTo, as in clojure

Thinking about it more, I think I like ``use`` better than ``on``.

**Comment by bluenote10** [comment]
I'm not so sure about macro based solutions. To me, one of the most important aspects of method chaining is to get auto-completion. Especially when working with unknown interfaces of third-party libraries it is a huge productivity boost for me.

I guess with the proposed macros we would never reach the great feeling of typing `.` and seeing the entire API when writing chaining expressions -- basically the compiler only sees some untyped expressions and cannot suggest completions. In practice, I already see myself temporarily copy pasting the expression on the left hand side into the line above where I can use `.` to explore the API. Doing this repeatedly on every method ruins the usual flow of chaining.

What about keeping it simple? Couldn't we simply do `a.dup().insert(1).sort()` so that we are all the time operating on something the compiler understands?

**Comment by Araq** [comment]
> Couldn't we simply do a.dup().insert(1).sort() so that we are all the time operating on something the compiler understands?

``insert`` returns ``void``, so no, this wouldn't work without a language extension or duplicated APIs.

> I guess with the proposed macros we would never reach the great feeling of typing . and seeing the entire API when writing chaining expressions -- basically the compiler only sees some untyped expressions and cannot suggest completions.

A very good point but once these macros become standard, nimsuggest can cheat and understand them and offer good auto-completion.

**Comment by bluenote10** [comment]
Maybe that can be solved by introducing the convention that inplace modifying methods return discardable `Self`?

**Comment by Araq** [comment]
And then ``dup`` still has the tool support problem? Please keep in mind that ``dup`` is the really useful feature here as it allows us to remove ``sorted`` et al from the stdlib.

**Comment by akavel** [comment]
`<bikeshedding>`

Would like to add an alternative name `tweak` (or maybe `edit`) for consideration for the chaining macro; personally I find the `use` one confusing. Sample block syntax:

```
tweak w:
    setColor(green)
    setVisible(true)
```
----
As a side note, as far as syntax, I'm also somewhat pondering whether I'd like comma-separated for the inline variant?

    w.tweak(setColor(green), setVisible(true))

The benefit in my eyes being that it seems to me to look a bit more similar to the block syntax.
`</bikeshedding>`

You're obviously free to completely disregard this comment, given it's basically pure bikeshedding!

**Comment by Araq** [comment]
Actually I'm thinking about ``w.use(setColor(green), setVisible(true))`` (commas instead of dots) because it avoids some ambiguities.

**Comment by akavel** [comment]
(to clarify, the confusion I'm having with `use` is that it seems to me to imply a different kind of relationship; as in `<who> use <noun>`, not `<who> use <verb>`; one more idea that came to me now would be maybe `apply`?)

**Comment by mratsim** [comment]
> Maybe that can be solved by introducing the convention that inplace modifying methods return discardable `Self`?

This is a bad convention because in many cases you would want to return an Error enum or a Result/Either type.

**Comment by jyapayne** [comment]
If we had a modification to the current implementation of star operators for term rewriting macros, we could have something like (non working example):

```nim
import macros
import algorithm

macro `|`{*a}(a: untyped): untyped =
  result = newNimNode(nnkStmtList)
  let firstNode = nodes[0].copy # the first argument or object
  for i in 1 ..< nodes.len:
    let call = nodes[i].copy
    call.insert(1, firstNode)
    result.add(call)
  result.add(firstNode)

let arr = @[1, 2, 3, 4, 50, 6, 7, 8, 9]

let result = arr | sort() | reverse()
```

**Comment by jyapayne** [comment]
Actually, you can do something like this as a workaround (hacky):

```nim
import macros
import algorithm

var firstObj {.compileTime.}: NimNode

macro `|`(a: untyped, b: untyped): untyped =
  if firstObj.isNil:
    # Store the first left side arg, which is
    # our object
    firstObj = a.copy

  let
    leftCopy = a.copy
    res = b.copy
  res.insert(1, leftCopy)

  result = newNimNode(nnkStmtList)
  result.add(res)
  result.add(firstObj)

proc main() =
  var a = @[1, 2, 3, 4, 50, 6, 7, 8, 9]
  echo a | sort() | reverse()

main()

# Outputs:
# @[50, 9, 8, 7, 6, 4, 3, 2, 1]
```

**Comment by Clyybber** [comment]
@jyapayne Thats exactly what `sugar.outplace` does :)

**Comment by jyapayne** [comment]
> @jyapayne Thats exactly what `sugar.outplace` does :)

Yep, just thought it looks cleaner and clearer what is happening with the pipe operator. But I didn't read the first part about not wanting a unary operator. I guess you also can't use the unary operator in a block.

@Araq For my comment on what I like from the options, I like `dup`, but `use` is weird. `chain` sounds much better :)

**Comment by Clyybber** [comment]
Yeah, outplace was kinda designed for use as an operator. Thats why calls with it "miss" the first argument, like the method call syntax.

**Comment by mratsim** [comment]
The pipe operator can probably be sugar, arrow would be fine too but precedence is wrong

**Comment by c-blake** [comment]
I vote for commas not dots as in `a.dup(sort, reverse)` or even `a.dup sort, reverse` which I think would also work as expected.  I think that reads *exactly* like what happens under the covers.  Why, it could hardly be mistaken by a newbie to the notation, IMO.  Since `sort` returns `void`, a period (`.`) there makes it seem wrong..as if "this magic dup thing is creating return types to chain or something". The action/magic, though, is not with the return type but the first argument.  The analogy to the block notation is also very strong where someone could say `a.dup: sort; reverse`..just semicolons or newlines instead of commas which all sort of like "weak-ish separators".  I don't have much opinion about the `use`/`with` part.

**Comment by c-blake** [comment]
If you really wanted, I suppose you could put periods before each and every call *as well as* having comma separation, but that might be a bit much for some tastes. { I.e. `a.dup(.sort, .reverse, .yadda, .yadda)` }

**Comment by c-blake** [comment]
And if people  think "dup" is too brief (I don't mind!), you could call it "uponDup"  or "onDup".  I cannot imagine thinking `onDup(a, sort(), reverse(), ..)` would mean anything other than I believe the intended meaning here.  The on emphasizes "action" part and the "dup" the object of the action being a copy.  "ondup" all lowercase is also not a word in English.  So, shift-key-haters would have no real issue.  I also think "onDup" would be a rare variable name/other user-code function name.  "dup" might be common in some code..Maybe even as the name of a duplicate/copy making it confusing.

That the expression returns the duplicate `T` is also pretty intuitive.  What else would you be doing? duping to a discard only engaging side effects or something weird?  Nah.  The natural reading is the right reading.

No more `*ed` sounds great to me.  Less to remember and no weird participle games.  My own run-in with that was `math.cumsummed`. ;-)  The word "dup" in there (vs operators) also highlights a potential performance bottleneck/optimization opportunity if the code does not really need a dup.  So, I think this would be a great way to go and hope something nice is agreed upon in almost any form.  Ok.  I'll shut up. :-)

**Comment by dom96** [comment]
@Araq why are you suggesting such ambiguous names? ``use`` is just as bad as ``on``. Why not use ``chain``? It's still short, unique and explains the semantics well.

**Comment by Araq** [comment]
For me ``chain`` has something to do with linked lists and doesn't fit well.

**Comment by c-blake** [comment]
`using` might be an alternative to `with`...Not that I have anything against `with`, though I did just wrote a macro called that for something slightly different (for direct field access of `x` above rather than proc-invocation upon `x`).  Related arguments about the old Nim `with` may matter for this one, too (either pro or con -- too similar but different or nicely similar but different, etc.)  I view it as less value-add than `onDup`.

**Comment by zedeus** [comment]
`using`, `with` and `on` are great for the block syntax, but they don't convey the semantics very well when using dot syntax. `x.using(setColor(blue))` doesn't naturally mean much imo, same for `with` and `on`. Sure `chain` has a connection to linked lists and hash tables, but I don't recall seeing `chain` in code involving those. It's mostly terminology related, and I'd argue the semantic connection to function chaining ("method chaining" in languages we don't speak about) is stronger.

**Comment by hlaaftana** [comment]
`using` is a keyword and [existing statement](https://nim-lang.org/docs/manual.html#statements-and-expressions-using-statement)

**Comment by c-blake** [comment]
Fair point about `using` already being used.  Hah.  Say that 10 times fast. In some broader sense (like Nim compiler code, 1000s of Nimble packages), almost nobody uses `using`.  Man, "us*" is Tongue Twister City. ;-)

I actually liked your `doTo` the best of the various proposals so far and should have said so.  Besides having clojure precedent, like `onDup` it has the same "two word structure" which I think helps emphasize what is happening under the covers with both a target and series of actions.  I that target object - action dichotomy is why people lean towards operators like `|` or `|>` and such for these things instead of regular words, but a couple of two-three letter words can convey more meaning than a single highly overloaded word like `chain`.

(`dupDo`, `doTo`) might also be nice pairing maybe called "the do's".  In `dupDo` the "dup" half of the word binds left or first argument and the "do" part binds right or the rest list of parameters. (`dupDo`, `toDo`) would be more self-consistent, but "todo" kind of collides to "to do lists" and other semantics.

Or reverse transforming yields my current favorite, (`onDup`, `onDo`) with the pair affectionately referred to as "the on's". ;-)    I like the left-right visual binding structure of "the ons".  `someVar.onDo set, poke, prod...`, `someArray.onDup sort, reverse, select, ... `.  Feels close to magical pseudocode that just does what it looks like which I think is the desirable target in program notation.  If commas are the separator then maybe if things have only 1 argument parens wouldn't even be needed.  But morning coffee can support only so much bikeshedding. ;-)

**Comment by Araq** [comment]
I'm strongly in favor of ``,`` now and don't mind to use the word ``chain`` if it helps to settle the case. So far most people like ``dup``, @c-blake so I see no reason to use uglier camelCase variations.

**Comment by c-blake** [comment]
Fair enough.  Just putting ideas out there.

**Comment by c-blake** [comment]
FWIW, I think both look fine in all lowercase, too..`ondup`, `ondo`, but that may be just me and I also don't mind just `dup`.

What I don't like about `chain` is that it means something just different enough to be confusing in this proposal than in its more common usage.  What is a "link" for this current "chain"?  In linked lists it's a pointer.  In call chains like `ob.poke().prod()` in other langs or even Nim where people conventionally return handles to mutable things, the link is the object handle explicit in the syntax which might even *vary* from call to call. In both cases the links are explicit.

In this proposal there are no explicit or implicit "links"..just successive void returning operations (which one reason why comma looks good, I think).  So, "chain" invites a question to which the only answer is something like "in an unrelated convention of procs returning mutable handles to some same underlying object as common in other-language-xyz that has no keyword arguments or outside the stdlib package-pdq" or something elaborate and seemingly off topic like that.

Anyway, I'm unlikely to use it anyway.  So don't worry about me liking "chain" much.  I prefer "omnibus interfaces" where you can use just one call to set various things like `w.set(color=green, position=(10, 20), visible=true)`.  There again, comma is the nice delimiter and it's usually clear when you need parens.  I think this sort of "call chaining" in other programming environments is almost always just a substitute syntax for keyword arguments/named parameters which Nim already has a better version of.  There is no temptation to put control flow in keyword args either.  So, the one question that already came up in this thread just wouldn't.  I think `dup` is good value add/API reduction.  I am less sure `chain` doesn't encourage otherwise-less convenient APIs with baggage from less expressive languages, but I also realize Nim is a Big Tent kind of language supporting much flexibility in programming styles/conventions.

**Comment by hlaaftana** [comment]
I would like to say `using` is very useful for writing wrappers, especially in JS where you have to do them by hand

**Comment by c-blake** [comment]
I could see that.  I could also see this new "chain/ondo/doto" thing being useful if you wanted to make wrappers of APIs for langs which have no kw args where on the Nim side they return `void`.

**Comment by Araq** [comment]
> I think this sort of "call chaining" in other programming environments is almost always just a substitute syntax for keyword arguments/named parameters which Nim already has a better version of. 

Indeed chaining is better avoided in Nim, keyword arguments or ``varargs`` are better solutions. Maybe it means that ``chain`` should be in separate module explaining the idiomatic Nim solutions and ``dup`` should be part of sugar.nim.

**Comment by c-blake** [comment]
That separation/explanation would make sense to me.  Others can/should speak up, but I think most interest in the operator versions, the stdlib, and this new RFC is all in `dup`.  I think it's much less hypothetical that `dup` will be popular/stick around in `sugar`, while chain/ondo/doto might need more iteration.

**Comment by c-blake** [comment]
Besides field setting, another application of chain/upon would be `ob.upon: phase1; phase2` or `upon ob, phase1, phase2`, maybe all guarded by an outer `try` for error handling.  It may be especially rare that such is popular without control flow, though..Why else separate phases/operations? I'd expect that feature request would arise again and again.

BTW, only 15 "upon"s in Nim source, our favorite English text corpus, while 76 "chains", and several thousand "with"s and "on"s. So, quantitatively, "upon" is over 5X better than "chain"! (kidding, it's all obviously pretty subjective..but sometimes numbers do sharpen focus). There are, of course, 0 "ondo"s and only 13 "dup"s.  Scarcity could mean ugliness..but maybe not. :-)

**Comment by Varriount** [comment]
Hm. Both `on`, and `upon`, remind me of event systems. "On this, do that".

I prefer "chain" and `dup` (though I'm not entirely happy with the latter - I thought `outplace` was fine).

@Araq @c-blake While keyword arguments are useful, keep in mind that both the number and order of keyword arguments a function has are static. There are design patterns where both these limitations would prevent using keyword arguments

**Comment by exelotl** [comment]
I agree that `on` is better suited for event-like stuff. +1 for `chain` and `dup`

**Comment by c-blake** [comment]
Number & names are indeed static, but arbitrary order is one of the bonuses of keyword arguments.

I still think call chaining is slightly off semantically in just enough of a way to confuse - in actual call chaining you link output of one call to the input of the next.  The output object could even potentially be *different* than the input and is only ever "always the same" by convention.  Here the link is the just the macro more inflexibly always using the same object.  So to me, "chain" does not clearly describe what this proposed macro does.  @Araq's original `operateOn` does, but I guess that has ugly camelCase.  (Heh...not a serious proposal but operateOnObject could be abbreviated "ooo" and that would probably not collide with anything.)

`apply` is closer..though really this is kind of the "dual" of already existing `sequtils.apply` (which applies one op to many obs instead of applying many ops to one ob).  That dual is mathematical, though.  In human language they're kind of the same thing and neither is "chaining" anything (except maybe "chaining activity" which literally *almost all* code does).

**Comment by c-blake** [comment]
In case people think I'm making this up, wikipedia at least agrees with me that this is what people usually mean by "chain": https://en.wikipedia.org/wiki/Method_chaining - not what the proposed macro does.  So, what do you tell someone new to the facility in Nim?  Well, it's sort of usable in a way similar to "chain"ing elsewhere, but without "links" or a chain really, instead with void return values.  Sounds tricky to get across to me.

This also raises the question of whether the macro should try to `auto-discard` non-void return values which I don't think has yet come up in this RFC and I suppose comes up with `dup` as well.

**Comment by akavel** [comment]
As I often do in cases where I'm not sure what word to use, I tried to search a bit in a thesaurus for some more inspiration and brainstorming; thus, some more words (some I like more, some less):

some verbs: `adjust`, `amend`, `alter`, `fixup`, `mutate`/`mut`, `perform`, `execute`/`exec`; `oust`, `mend`, `patch`, `sway`, `mold`

some prepositions: `onto`, `atop`, `over`, `about`, `into`, `through`/`thru`, `within` (apparently there are just 150 prepositions total in English?

**Comment by zedeus** [comment]
@c-blake it's true that the macro doesn't literally do chaining, but afaik it was created to support chaining without all the `-ed` variants that make native chaining possible, it's like a magic chaining macro that does all the intermediary work for you. This is less obvious with `,` and block syntax instead of `.` but I don't mind that. So, I don't think `chain` is misleading since it describes what the macro is conceptually (and semantically?) going to produce. And like the OP states, it introduces `chaining` via a macro for functions that don't support it. You could again argue that it isn't actually doing chaining, but if it were then there would be no reason to use the macro.

**Comment by c-blake** [comment]
@zedeus - the ever growing set of `-ed` past participle procs in the stdlib are to be subsumed by `dup` (which seems less naming contentious to all concerned), not `chain`.  `settedColor` was never in play. :-)  (Yes, I know "set" is its own past participle in English...Just being funny.)

As I mentioned, almost all code conceptually chains some described activity.  At some level you could use "chain" for almost anything. We don't usually refer to semi-colon as a "statement chaining operator" or comma as an "argument chaining operator", or every macro as `graft`, `splice`, `fuse`, etc., { whip out the thesaurus :-) } though that's what they do to ASTs.

I just think there are subtle but real semantic diffs between this macro (which is like a series of calls on a shared first arg) and the specific semantics of typical call chaining (closer to @bluenote10's discardable self which requires no macro but does chain) that makes `chain` a more confusing choice than `onto`/`upon`/ `operateOn`/`doTo`/`opOn`/`onDo`/`doOn`/`firstArg`.  We don't have to agree, though.  I'm just trying to help.  I doubt I will use this much/ever (and few others may use it).

**Comment by akavel** [comment]
Ah, and I just realized: if `using` is already a keyword, then `use` in my opinion is risky of being confusing.

**Comment by Araq** [comment]
I've settled on ``dup`` and ``with`` fwiw.

**Comment by Araq** [comment]
The proposal turned into https://github.com/nim-lang/RFCs/issues/193

**Comment by bluenote10** [comment]
> This is a bad convention because in many cases you would want to return an Error enum or a Result/Either type.

Mixing mutable side effects and return values isn't the most intuitive interface to begin with. How will the macros deal with it? It is either
- discard (swallow errors?)
- forbid (not chaining possible)
- somehow expose value (complicated, I don't see how that would be chainable)

@Araq Maybe this can be specified in the updated RFC?

> nimsuggest can cheat and understand them and offer good auto-completion.

I'd be surprised if this works well, especially because IDEs typically don't auto-trigger completion on white space.

> I've settled on dup and with fwiw.

Hm, that might be confusing for people associating `with` with context management / RAII (feature request [here](https://github.com/nim-lang/Nim/issues/6471)).

Overall I'm not a fan of these solutions. I thought that the introduction of move semantics in Nim would allow for real chaining by getting rid of chaining showstoppers: inplace mutable functions. In Rust there is no participle duplication `sort` vs `sorted` -- functions basically have `sorted` semantics (called `sort` in Rust, just to give the Nim equivalent), but without any overhead because they consume the input: `vec.sort()` behaves like an inplace sort, `vec.clone().sort()` is an outplace sort, which makes chaining trivial. @mratsim Note that your example of a modified collection + return value also works fine in this model, e.g. by returning a tuple -- the chaining can continue on either one / both as needed.

**Comment by Araq** [comment]
> (called sort in Rust, just to give the Nim equivalent), but without any overhead because they consume the input: vec.sort() behaves like an inplace sort, vec.clone().sort() is an outplace sort, which makes chaining trivial.

That doesn't solve the "append semantics" problem though. Everything that returns a string is better written with append semantics. Consider that ``a & b`` is ``a.dup(&= b)``.

> I'd be surprised if this works well, especially because IDEs typically don't auto-trigger completion on white space.

But the trigger would be the comma or "(". Not sure I understand you.

> Hm, that might be confusing for people associating with with context management / RAII (feature request here).

Good point but we have destructors for RAII.

**Comment by bluenote10** [comment]
> That doesn't solve the "append semantics" problem though.

Why can't `&` have move semantics? In Rust:
```rust
let a = "asdf".to_string();
let b = "asdf".to_string();
let c = a + &b;
println!("{}", c); // asdfasdf
println!("{}", b); // asdf, works because not moved
println!("{}", a); // not possible, a was moved
```
Essentially the move semantics are append semantics because the left-hand-side gets moved.

> But the trigger would be the comma or "(". Not sure I understand you.

Typically there is another space after pressing `,` which doesn't trigger completion automatically in most IDEs. Also with block syntax it's after a `<ENTER>` or `<TAB>`, which is also not a common place for completions.

**Comment by Araq** [comment]
> Essentially the move semantics are append semantics because the left-hand-side gets moved.

Good point. Not sure if it produces good results in practice, consider:

```nim

proc toPretty(result: var string, node: JsonNode, indent = 2, ml = true,
              lstArr = false, currIndent = 0) =
  case node.kind
  of JObject:
    if node.fields.len > 0:
      result.add("{")
      result.nl(ml) # New line
      var i = 0
      for key, val in pairs(node.fields):
        if i > 0:
          result.add(",")
          result.nl(ml) # New Line
        inc i
        # Need to indent more than {
        result.indent(newIndent(currIndent, indent, ml))
        escapeJson(key, result)
        result.add(": ")
        toPretty(result, val, indent, ml, false,
                 newIndent(currIndent, indent, ml))
      result.nl(ml)
      result.indent(currIndent) # indent the same as {
      result.add("}")
    else:
      result.add("{}")
   ...
```` 

vs 

```nim

proc toPretty(result: var string, node: JsonNode, indent = 2, ml = true,
              lstArr = false, currIndent = 0) =
  case node.kind
  of JObject:
    if node.fields.len > 0:
      result = result & "{"
      result = result.nl(ml)
      var i = 0
      for key, val in pairs(node.fields):
        if i > 0:
          result = result & ","
          result = result.nl(ml) # New Line
        inc i
        # Need to indent more than {
        result = escapeJson(key, result)
  ...
```

But yeah, it would technically work. Rust's ``Vec::push`` doesn't return its consumed vector either fwiw. The friction between inplace vs outplace is a real thing, even in Rust.
