### ISSUE TITLE
Every value should be printable with echo

### ISSUE THREAD

**Issue by krux02** [nim-lang/RFCs#203]
In my own experience ``echo`` is used most heavily for debugging purposes. It is part of the _hello world_ program, and then it is continuously used to explore the programming language and long the behavior of the program. It is also used to put values into error messages, for example in ``raise newException(KeyError, "key not found: " & $key``). But some types are just not printable with ``$``. This usually comes as a surprise, especially in generic code, as the majority of types do already have a ``$`` overload. 

The solution to the problem is to provide a generic solution of ``$`` for every type that the Nim language allows, so that ``echo x`` and ``"key not found: " & $key`` will always compile, no matter what the value is. 

After all these overloads would be need an addition:

## `ref`/`ptr` types

`ref` types are the natuarl thing to use in Nim, when the code is inteded to be executed on a javascript vm, as this is what the backend naturally supports and doesn't need to be emulated. But the big disadvantage of using a `ref` type is that it isn't printable with `echo`. My suggestion is to provide the following implementation:

```nim
proc `$`*[T: ref | ptr](arg: T): string =
  if arg == nil:
    "nil"
  else:
    $arg[]
```

This implementation is able to print `nil` when required, but otherwise the output won't make it obvious that it prints a pointer value. Sometimes people care about the pointer values and they want to see them. But pointer values are at least 16 characters in hex and therefore very verbose in the output. To my experience people usually really don't care about the pointer value. As long as it points to something valid, it should print just that, not some hexadecimal string.

#### Dealing with Cycles

The current implementation of  ``$`` on objects iterates all printable fields recursively. This is problematic, as with this RFC it will run into infinite recursion if the value forms a pointer circle. An because ``$`` is located in ``system.nim`` and no further imports are allowed, a hash map to store previously visited nodes can't be used.

However there is already a nice static analyser built into the compiler to detect if a type is even able to form cycles: [`canFormAcycle`](https://github.com/nim-lang/Nim/blob/86b9435138109441ffaa5a9c221f641ec3ed4b05/compiler/types.nim#L376). Pointers to such recursive types could then be printed as just `...` like non printable types are represented right now. This isn't very helpful, but still much more helpful that printing all `ptr`/`ref` types as "...".

## Distinct Types

It is easy to implement `$` for distinct types:

```nim
proc `$`*[T: distinct](arg: T): string =
  $distintcBase(T)(arg)
```

The question though remains, should distinctness simply be shaved off here? After all the programmer explicitly asked for a new incompatible type. @Araq mentioned this could be dangerous because of SQL injection. But I don't think this is really a problem. After all a distinct string remains a distinct string and it is not automatically converted to ``string``. It is only converted in `echo` because it explicitly attaches a `$` conversion to every argument. Maybe a distinct string should be quoted and not just printed. Or it should be altered in some other way. But that is still open to discussion. But I do think something should be printed.

## Pointer

The type ``pointer`` doesn't have any content it can print. The only thing that it can print is the value of the pointer itself. Earlier I argued printing actual pointer values is verbose, but here there is nothing else that can be printed. So it should be done. After all fields that are of type ``pointer`` are rare.

## Callbacks

Unfortunately I don't have a good solution for `proc` value. I can check if they are nil and print "nil" if they are nil. But unfortunately I cannot print anything useful in the other case. A `cdecl` callback can be cast to a `pointer` and the address can be printed. But that doesn't work for closures. `gdb` can print even the name of a cdecl callback, but I don't know how to do that in Nim.

I have a PR where this RFC has been implemented. It also shows how code would be simplified in the standard library and the compiler when after all a `$` is available for everything.

**Comment by krux02** [comment]
@Araq You asked for this RFC here. Now you can complain about it here. 
@timotheecour You commented on my PR already. Here you can comment on the RFC. Please try to break it. I would like to know where it falls apart.

**Comment by 0xACE** [comment]
Regarding distinct types: I'd suggest this RFC does not implement the stringify procedure. As the manual essentially promises that a distinct type will not implicate conversions to the base type which this RFC would violate.

**Comment by krux02** [comment]
@0xACE regarding "implicit conversion". This is not an implicit conversion. This is after all an explicit conversion to string with the `$` operator. And the `$` operator is injected only for specific cases.

**Comment by timotheecour** [comment]
## recursive expansion of ptr/ref by default is a bad idea
* eg, printing `PContext` generates a string of **2.1MB** when you insert a `echo c` debugging statement and compiling compiler/nim.nim
See snippet here: https://gist.github.com/timotheecour/c97476b7cdf02ea48c56a1c4c480c198
Not very useful for debugging.
(I had to fix some stuff otherwise it wouldn't compile in your PR)

## A hash table is the only sane way to deal with ref/ptr aliasing
Static detection of cycles (as you're using in your PR) is the **wrong criterion to use**, and has both false positives and false negatives in terms of what gets duplicated.

Instead, the correct way is to do what a cycle-aware serializer does, for example **depth first search visit of each node, marking the ones already visited to avoid duplicates**, using a hash table to mark node addresses. That's precisely what I've implemented in my own pretty printer.

The criterion you're using allows duplicate printing of nodes when you have a DAG, eg: see example2 I gave in https://github.com/nim-lang/Nim/pull/13687#issuecomment-601112539, it causes duplicate printing as follows:
```
(bar1: (s: "some long string that gets duplicated"), bar2: (s: "some long string that gets duplicated"), x: 12)
```

And on the other hand, it doesn't print nodes that should be printed (aren't duplicates), eg:
```nim
block:
  type Foo = ref object
    id: int
    next: Foo
  let a = Foo(id: 10, next: Foo(id: 11))
  echo a
```
prints `(id: 10, next: ...)` where `next` is not expanded even if there's no address duplicate.

## proposal
it's impossible to satisfy every use case with builtin `$` so we should have a builtin `$` (ie, imported from `system`) that does the simplest possible thing with no customization possible, and a separate module that can be customized for more advanced / customizable prettyprinting.

### proposal part 1: system.$
* `$` should "work" (even if it means only prints some address) on every type (only part of your proposal I agree with)
* only top-level ref/ptr should expand (no recursion), so that:
```nim
type Foo = ref object
  id: int
  next: Foo

let a = Foo(id: 10, next: Foo(id: 11))
doAssert $a == 0xdeadbeef->(id: 10, next: 0xdead1234)
doAssert $a[] == (id: 10, next: 0xdead1234->(id: 11, next: nil))
```
* proc pointers prints address using `rawProc`
* closures prints address using `rawProc` + `rawEnv`
* distinct prints using `...`
* all those are subject to usual overloading rules in case of `$` overload in scope

### proposal part 2: std/prettyprint module
Since we're using a separate module, we can have more dependencies, which simplifies implementation.
```nim
type Option = ref object
  depth: int # how far to recurse
  showDistinct: bool # when true, if no `$` overload exists for a distinct type, print via undistinct
  fpFormat: string # customizes FP printing eg `"%.02f"`
  # etc... that customizes prettyprinting

pretty[T](result: var string, a: T, options: Options = nil)
template pretty[T](a: T): string = pretty(a) # for convenience since so common
```
all overloads are `outplace` form and there's a single `inplace` form, just like in https://github.com/nim-lang/RFCs/issues/191


* floats print using `ryu` (probably too complex for default inclusion in `system`)
* distinct can be shown via undistinct
* we use a `Hash[ByteAddress]` to mark already visited addresses and avoid printing duplicates

I've already implemented that in a private project, so I know it's quite doable. It enables customizable prettyprinting, eg to terminal, using colors, or to html with dynamically expandable nodes etc.

![image](https://user-images.githubusercontent.com/2194784/77305710-c51a4380-6cb3-11ea-81cd-3762c8000400.png)

**Comment by 0xACE** [comment]
@krux02 
> @0xACE regarding "implicit conversion". This is not an implicit conversion. This is after all an explicit conversion to string with the `$` operator. And the `$` operator is injected were dollar oparator application is exlicitly requested.

You are describing the problem itself. Here the `$` operator is making an **assumption** about a `distinct` type to which the user **explicitly** declared to have absolutely no relations to its basetype, which includes the parent `$` operator.

The `distinct` type is meant to be **incompatible** with its base type, implementing this RFC for `distinct` types would be a clear violation of this promise.

I understand that implementing this would help with a "resistance free" programming approach for `nim`, but it does so at the cost of `nim`s integrity. Vague implementations like these would not lead to a great design in formal systems where soundness is desired to be preserved. It is called `distinct` not `distinct_but_inherit_$`.

**Comment by zah** [comment]
Two thoughts to share regarding this proposal:

1) Perhaps it's a bit unfortunate that we are used to debugging things with `echo`. `echo` is considered to have side-effects, which makes it unusable with the `func` keyword. `debugEcho` works there, but it's a bit of a mouthful to type. If we had the habit of using another special function with a short name such as `dbg` that has a developer-friendly print out such as the one shown by @timotheecour, then this debate will be much less controversial ("of course `dbg` can print everything, it show you the memory contents of objects").

2) "Every value should be printable" is a case of what I call "default implementation of a generic proc" and unfortunately the language has some unresolved design issues with such procs. The [generic sandwitch problem](https://github.com/nim-lang/Nim/issues/11225) or a missing import makes it very easy for the compiler to pick the default implementation over a more specific and correct overload supplied by the user. Perhaps printing things to screen is not so mission-critical task and we can tolerate the risk, but we've seen some very nasty and difficult to track bugs stemming from this problem. I've proposed a potential solution that re-defines the `method` keyword to introduce [user-supplied type-bound operation](https://github.com/nim-lang/RFCs/issues/139#issuecomment-490841745) that will work outside of the context of type hierarchies and that won't suffer from the lexical scope issues.

**Comment by Araq** [comment]
> It is called distinct not distinct_but_inherit_$.

I think this argument is so strong that I cannot imagine a stronger argument that is in favor of "$ for distinct".

> proposal part 2: add std/prettyprint module

Yes! That's the solution we should have. Zahary's ``dbg`` is probably the same idea.

**Comment by mratsim** [comment]
Please don't print `distinct` type.

Currently the best way to create secret cryptographic keys is to use a `distinct` type and prevent printing and comparing them.

Assuming you somehow import the type and but don't import the `==` or the `$` overload, the `distinct` will at least prevents the code from compiling.

i.e. if you allow printing `distinct` we would need a `secret` modifier that would behave the same as today to keep providing the same guarantees for crypto libraries.

**Comment by andreaferretti** [comment]
It is not a great guarantee, after all. If you have access to an instance of a key, you can take its address and read the raw memory. Moreover, you are trying to protect against an attacker who is... writing the application?

**Comment by mratsim** [comment]
It's to protect against misuse. Most of the cryptographic problems currently are due to misuse of libraries API, and anything that help against such misuse is a win see https://www.usenix.org/legacy/publications/library/proceedings/sec02/full_papers/gutmann/gutmann_html/index.html

**Comment by Araq** [comment]
1. std/prettyprint is an excellent idea, please let's have that.
2. "Every value should have $" is officially rejected.

**Comment by zah** [comment]
`pp` would be a nice name for the pretty-print function. IMO, it should be considered `noSideEffect` like `debugEcho`.

**Comment by metagn** [comment]
Fwiw we have packages for this, like https://github.com/treeform/pretty
