### ISSUE TITLE
rebasePath

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#256]
## proposal
add this to std/os
```nim
proc rebasePath*(path, oldBase, newBase: string, check = true): string =
  if path.isRelativeTo(oldBase):
    result = newBase / path.relativePath(oldBase)
  else:
    doAssert not check, $(path, oldBase, newBase)
    result = path
```

**Comment by Araq** [comment]
1. You could add some use cases.
2. The ``check = true`` seems a bit problematic to me because you turn the check failure into an untracked AssertionError exception. However, it is better than a hypothetical ``proc rebasePath*(path, oldBase, newBase: string, check = true): string {.raises: ValueError.}`` solution which then cannot really fail when you pass ``check = false``. But maybe that's an indication that we want two procs rather than one.

**Comment by timotheecour** [comment]
=> see https://github.com/nim-lang/Nim/pull/15514
