### ISSUE TITLE
can iterators be implemented as a library solution / syntax sugar over regular procs?

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#272]
see https://github.com/nim-lang/Nim/pull/15655 for a simple macro that allows defining something that acts very similar to an iterator:
* it supports break, continue, multiple iterator arguments, can yield a single or tuple of arguments

Not only that but it solves major long existing limitations with iterators, eg:
* closure iterators can't be used in VM
* closure iterators can't be used in js

this is not a complete 1:1 replacement (see limitations below) but could become one.
This could potentially be a basis for replacing iterators with regular procs + syntax sugar, which would simplify nim language by removing all custom compiler code handling iterators.

## example
```nim
import std/iterates

# analog to:
when false:
  iterator myIter[T](s: seq[T]): auto =
    for ai in s: yield ai*10

proc myIter[T](s: seq[T], cont: proc(_: T)) =
  for ai in s: cont ai*10

# analog to:
when false:
  iterator myIter2(a, b: int): auto =
    for ai in a..b:
      yield (ai, $ai)

proc myIter2(a, b: int, cont: proc(a1: int, a2: string)) =
  for ai in a..b:
    cont ai, $ai

template main() =
  block:
    var ret: seq[int]
    # analog to:
    # for x in myIter(@[2,3]):
    #  ret.add x
    for x in iterate myIter(@[2,3]):
      ret.add x
    doAssert ret == @[20, 30]

  block:
    var ret: seq[(int, string)]
    for k,v in iterate myIter2(2,5):
      ret.add (k,v)
    doAssert ret == @[(2, "2"), (3, "3"), (4, "4"), (5, "5")]

static: main()
main()
```

## note
* the following maps `{.closure.}` iterators only, but with alias PR (https://github.com/nim-lang/Nim/pull/11992), we should also be able to map `{.inline.}` iterators just as well (since we'd be able to forward a template (instead of a proc) inside the `iterate` macro); I can provide more details if this is unclear
* D ranges is still the superior abstraction, offering better composition and support for 0-cost lazy functional programming (unlike sequtils + other nimble packages which have fundamental limitations); note that the iterator syntax sugar would still be usable for simple ranges.

## limitations
* this macro is not a complete replacement of iterators but could be improved to narrow the gap: these are not yet supported: `finished`, `next`.
* type inference could be improved so that the macro would be able to infer the iterator yield type, this is IMO possible if https://github.com/nim-lang/Nim/pull/11754 is merged; this should enable this to work: `typeof(block: (for ai in iterate a: ai))` which currently doesn't work; and hence would enable `toSeq`
* syntax sugar could be added to close the gap with iterators so that `for ai in iterate a` could be written as `for ai in a`; likewise, iterator definition could be mapped to a proc as defined above.

## EDIT
* I've now also implemented `continue` and `break`, see PR

**Comment by nc-x** [comment]
Even if this works, I would prefer the core language to be implemented in the compiler and not through macros (for better compile times and sane error messages), at least unless and until the macros are mapped to compiler plugins which should improve the performance of macros significantly (see v2 milestone),
![image](https://user-images.githubusercontent.com/43749640/96580929-aa19bb80-12f6-11eb-9e85-34f6bdfed622.png)

**Comment by Araq** [comment]
> D ranges is still the superior abstraction, offering better composition and support for 0-cost lazy functional programming

It's still worse as there is no ownership system so you're left with a tracing GC or more-expensive-than-you-think-it-is reference counted slice type which diverges quite a bit from the naive (ptr, len) pair implementation.

**Comment by mratsim** [comment]
I'd like a report on CPS, what was tried, what is missing so far so that we can evaluate this RFC with its most obvious alternative (besides what is implemented today).

**Comment by disruptek** [comment]
The initial CPS impl in `master` represents an `untyped` macro.  The tests and demos work.

The `typed` version (I think it's in a `typed` branch), solves several performance and ergonomic warts but doesn't work yet due to apparent compiler bugs, at least one of which requires a breaking fix.  I think it's in 1.4, but I'm honestly unsure.

What remains to be implemented (or demonstrated, at least):
- thread migration using isolate semantics
- syntax polish so you can `continuation()` or whatever
- rvalue shim so you can `let foo = continuation[]` or whatever
- rewrites to support/optimize control-flow

Maybe @zevv has some clearer ideas about what's missing; this is just the stuff off the top of my head.

I personally really want properly bulletproof concepts so I can play with some ideas for _CSP_; the abstraction over _CPS_ where we'll implement go-channel/clojure-core.async-type machinery.

**Comment by zevv** [comment]
Right, @disruptek kind of tells it all. The Nim CPS project is basically an implementation of the mechanics described in the paper "Continuation-Passing C - Compiling threads to events through continuations". Linear Nim code is transformed into a number of separate procs that pass continuation objects among them. What used to live on the stack is now in the continuations, which allows non-linear code flow.

On top of Disruptek's CPS work I prototyped some basic constructs like:

- iterators
- async I/O
- coroutines
- goto
- exceptions

From a technical point of view, this all works, although the syntax is sometimes lacking or plain weird, still.

We are stuck for some time on motivation and a compiler bug, although I'm not even sure at this time what exactly the bug was (something sym vs ident, I believe). I think the goal was to prove this was all feasible and usable, but we already know that a definitive implementation should probably do the transformations in the compiler instead of using macros.

**Comment by timotheecour** [comment]
Can you share any relevant link?

**Comment by zevv** [comment]
TBH: I'm not sure if the above links actually compile with the current state of CPS - stuff was very much in flux, we had a few days of hacking frenzy but broke API's on the way a few times. But I'm sure the above snippets show the gist of what we were trying to do.

**Comment by disruptek** [comment]
There are two forms of bug that I consider blockers:
- proc arguments should be symbols for typed macros (fixed in 1.4?)
- ICE on substitution symbol for symbol or symbol for expression in macros

**Comment by timotheecour** [comment]
in https://github.com/disruptek/cps/blob/master/stash/iterator.nim instead of:
```nim
var a = counter(3, 7)


# Resume the iterator a bunch of times

var v = a.produce()

echo "produced ", a.produce()
echo "produced ", a.produce()
```

can you use `ForLoopStmt ` as I did in https://github.com/nim-lang/Nim/pull/15655 to enable the more idiomatic `for` syntax for the common case?

**Comment by zevv** [comment]
Hmm, it's all some time ago, so I'd have to get back into all that to tell, but I think with the for loop macro that should work...

**Comment by Araq** [comment]
This is not an RFC, this is an interesting question.

**Comment by timotheecour** [comment]
It's not just an "interesting question", the suggestion is that maybe the language can be simplified by mapping (via syntax sugar enabled by the compiler) the existing iterators to a pure library implementation, also fixing https://github.com/nim-lang/Nim/pull/15818 in the process.

**Comment by Araq** [comment]
Sure but an RFC is what you write *after* you have established that it's possible and a good idea. Then you write an RFC to convince others that we should change Nim.
