### ISSUE TITLE
Allow to specify type for unpacking assignment

### ISSUE THREAD

**Issue by al6x** [nim-lang/RFCs#339]
Currently this code would fail:

```Nim
let pair: (int, int) = (1, 2)
let (a, b) = (1, 2)

let (c, d): (int, int) = (1, 2) # <= Error
```

Would be nice if it would work.

**Comment by hlaaftana** [comment]
I would say `let (c: int, d: int)` looks better and you have to type less (and you don't need to support `auto`) but the structure of the AST for tuple unpacking would have to breakingly change for that (there is a reserved AST spot for a type which would only work for `let (c, d): (int, int)`), and `let (c, d: int)` could be interpreted as meaning the same thing as `let (c: int, d: int)` (because of other parts of the language that do this), so maybe you would have to support `let (c; d: int)`. It would also conflict with any intuitive possible method of named tuple unpacking.

**Comment by timotheecour** [comment]
let (c: auto, d: int)

**Comment by hlaaftana** [comment]
Partial current workaround:

```nim
((var c: int; c), (var d: int; d)) = (1, 2)
```

Has the caveat of having to be `var` and not `let`, but allows mixing new variables with old ones.

```nim
var a = false

(a, (var b: cstring; b), (var c: int; c)) = (true, "abc", 2)
echo a # true
echo b # abc
echo c # 2
```

**Comment by timotheecour** [comment]
how about simply:
```nim
var a = 1
(a; let b, var c) = (1,2,3)
```

and to allow types:

```nim
var a = 1
(a; let b: int, var c) = (1,2,3)
```

the syntax is as simple and flexible as it gets

**Comment by hlaaftana** [comment]
Sorry, I wasn't proposing anything or offering an alternative to the proposal, I was just saying how it's possible to get the semantics in current Nim. The only issue with getting the semantics beyond aesthetics is that you have to use `var`.
