### ISSUE TITLE
[RFC] Change int literal to number literal

### ISSUE THREAD

**Issue by PMunch** [nim-lang/RFCs#36]
## Problem
Currently there is an inconsistency in how types can be declared in Nim which is very confusing and unnecessary.
```
var a = 5 # Creates an int
var b: uint8 = 5 # Creates a uint8
var c = @[5] # Creates a seq[int]
var d: seq[uint8] = @[5] # Throws an error,  "Error: type mismatch: got <seq[int]> but expected 'seq[uint8]'"
```
This holds true for all container types. The problem here is that Nim treats all numerals found in code as an integer literal. The reason why `var b: uint8 = 5` works is because there exists an implicit converter from int literals to uint8.

## Proposal
What I propose is that int literals are changed to become a number literal. This pseudo-type will be kept unresolved for as long as possible, and only attempted to be converted into it's target type once it's required. This will require the compiler to treat them a bit differently from how integer literals are treated today, but the benefit to typing and code readability would, in my opinion, be worth it. I haven't looked at implementation details for this yet, and it might be incredibly hard to achieve, but if it's not I think this would be a welcome change in Nim.

**Comment by m-holger** [comment]
[Health Warning : I am a Nim newbie and do not really know what I am talking about]


If an "int literal" is a numeric literal that defaults to int, than there seems to
be an omission in Nim:  there is no genuine "int literal".

Should there be a `1'i` in the same way as for all the other integer types?

**Comment by krux02** [comment]
I recommend you to read this section that I recently wrote about how integer literals are teated in the compiler: https://github.com/nim-lang/Nim/blob/devel/doc/intern.rst#integer-literals.

I agree that the way how integer literals are handled is not good. But this RFC doesn't provide a solution yet.

**Comment by hashbackup** [comment]
I ran into something similar when trying out Nim for the first time recently.  This simple program does not compile:
```
import tables
var map = initTable[int16, int16]()
map[0] = 0; map[10] = 10
for i in 0..10:
  map[i] = i
```
Line 3 is fine but line 5 gives a compile error.  I realize that: a) 0..10 ends up being a subrange of type int; b) therefore i is an int; c) map[int] = int doesn't match the table's type, and might be bad because it could truncate an int value when stored into a map with 16-bit values.  But to most programmers I think this snippet looks fine and it is surprising that it fails.

Here's a related issue, to me at least:
```
import tables
var map = initTable[int, int]()
map[0] = 0; map[10] = 10
var i: int64 = 0
map[i] = i
```
I can understand why this should fail if built on a system where int is 32-bits.  But it seems odd that when int is a 64-bit integer, int64 and int are not compatible.  If i is declared var i = 5_000_000_000, i gets a type of int64 and the compile also fails, even though it would execute fine on a 64-bit system.  And it's not like this allows programs to run on either 32 or 64-bit systems, because this code:
```
import tables
var map = initTable[int, int]()
map[0] = 0; map[10] = 10
var i = 2_000_000_000
i = i * 3
map[i] = i
```
compiles on either 32 or 64-bit systems, but only runs on 64-bit systems.  So I don't understand the value of having int be a distinct type from both int32 and int64.

Here's how I conceptually expect integers to work:

1. An integer constant is either signed or unsigned.
2. The compiler figures out the minimum bits the constant requires, so 7 is type uint3, -7 is type int4, 0 is type uint1.
3. 0..10 is a subrange of [uint1..uint4], so the subrange type is uint4, the highest of the 2
4. uintX is compatible with uint>=X and int>X
5. intX is compatible with int>=X, but never uint as the sign could be lost
6. int is exactly equivalent to int32 on a 32-bit machine and int64 on a 64-bit machine

I'm not proposing that Nim allow var i: int7, but would like integers to behave in an intuitive manner.

**Comment by Araq** [comment]
> Here's how I conceptually expect integers to work:

Been there, done that, was worse than today's rules in practice. The only real issue here is https://github.com/nim-lang/RFCs/issues/149
