### ISSUE TITLE
mac/darwin-x64 prebuilt binary

### ISSUE THREAD

**Issue by DeanHnter** [nim-lang/RFCs#441]
### Summary
I would like a pre-compiled version of Nim available for macos x64.

### Description
Binary versions are currently available for windows/linux however the mac version has to be compiled from source adding extra steps when integrating nim into a CI system.

### Alternatives
I have already made my own repository to mirror, build and host a mac-os version but it would be simpler if it was available officially also if someone could let me know whether it is ok to self host the compiler this way on github publicly without any issues I would appreciate it.

https://github.com/DHunte/NimBuilds

**Comment by Yardanico** [comment]
https://github.com/nim-lang/nightlies/releases/tag/2021-12-14-version-1-6-48c62ca48bc1f0a0ff4bc891e720297b3e8e5c15

This repo makes new builds for devel, version-1-6 and some other branches. I can't say it's exactly "official", but it should be usable for your purposes.

**Comment by DHunte** [comment]
Hi,

Thank you those might be helpful in some way but the only problem i see might be that it isnt easy to increment the version number quite the same way the official release is : https://nim-lang.org/download/nim-1.6.2_x64.zip just swapping out the 1.6.2 is much simpler since it doesent have the date and a uuid that might change, even the package manager im using requires a standard major.minor.patch format only.

**Comment by Araq** [comment]
Nightlies are official and x64 is kinda deprecated by Apple, I think.
