### ISSUE TITLE
A built-in dynamic byte array type

### ISSUE THREAD

**Issue by archnim** [nim-lang/RFCs#455]
Hello world. I think that we should create a new built-in type for Nim, that provides out the box, all the basic bitwise operations (and, or, xor, shl, shr, etc...). The type should also comprise procs to generate different string representation of data, for display (binary string, octal and hexadecimal).

# Why I think it's ~~important~~ unavoidable
One of the most fundamental tasks in programming is raw data manipulation. A system-level language like Nim Must Not only make it possible, but also as easy as possible; because it's not just a secondary feature. People need it to create Multimedia codecs parsers, cryptographic algorithms, database management systems, and so much more !

# Details of the idea
I think that we should add to the standard library, a wrapper around seq[byte] (just like deques) that handles effortlessly arbitrarily long strings of bytes. I've already written a code that can be improved to become the new built-in library. My implementation of the concept is [here](https://github.com/archnim/bseq/blob/main/bseq.nim).

# Before/After examples
Here are few B/A codes to help realize how relieving such a library would be. To avoid writing all the code for reading and writing data into files, let suppose that the procs `rdf()` and `wrf()` allow respectively to read all the content of a file into a seq[byte], and to write all the content of a seq[byte] to a file. 

### Before
```nim
var
  data1 = rdf("data1.bin")
  data2 = rdf("data2.bin")
  merged: seq[byte]
  mx = max(data1.len, data2.len)
  mn = min(data1.len, data2.len)
  longuest: seq[byte]
  toup = 1

  if data1.len >  data2.len:
    longuest = data1
  else:
    longuest = data2

  for i in countdown(mx - 1, 0):
    if toup <= mn:
      merged.insert (data1[data1.len - toup] xor data2[data2.len - toup]), 0
    else:
      merged.insert longuest[longuest.len - toup], 0
    toup += 1

  wrf("merged.bin", merged)
```

### After
```nim
var
  data1 = rdf("data1.bin")
  data2 = rdf("data2.bin")
  merged: (data1.toBSeq or data2.toBSeq).data
  wrf("merged.bin", merged)
```

### Before
```nim
  var
    data = rdf("data.bin")
    to3 = 0
    temps = [0, 0, 0]
    temp: int
    arr: seq[string]
  for i in countdown(data.high, 0):
    temps[to3] = data[i].int
    to3 += 1

    if to3 == 3:
      temp = temp or temps[2]
      temp = temp shl 8
      temp = temp or temps[1]
      temp = temp shl 8
      temp = temp or temps[0]
      arr.add temp.toOct(8)
      temps = [0, 0, 0]
      temp = 0
      to3 = 0

  if to3 == 2:
    temp = temp or temps[1]
    temp = temp shl 8
  if to3 > 0:
    temp = temp or temps[0]
    if to3 == 1:
      arr.add temp.toOct(3)
    else:
      arr.add temp.toOct(6)

  reverse arr
  echo join arr
```
### After
```nim
  let data = rdf("data.bin")
  echo data.toBSeq.toOct
```

# Backward incompatibility
The concept itself doesn't introduce any backward incompatibility issue. My implementation introduces a shortcut operator (@:) to convert different data types to byte sequences. If somebody uses it already for another purpose, they should make sure, that the lib doesn't break their code.

**Comment by Clonkk** [comment]
Shouldn't this be implemented as a ByteStream, using the streams API for binary data?

**Comment by konsumlamm** [comment]
First of all, I don't think this justifies a new built-in type, or did you just mean a new stdlib type? Also, no other collection has a custom operator like `@:`, I think that would only be confusing.

I doubt that your use case needs a new type at all though. `and`, `or`, `xor`, etc. could all be implemented on `seq[byte]` instead. I don't see how Multimedia codecs parsers, cryptographic algorithms, database management systems, and so much more would need a new type that is just a wrapper around `seq[byte]` with some bitwise operations. That being said, the official https://github.com/nim-lang/bigints library already supports bitwise operations and shifting along with conversion to (and from) a string of base 2 to 36, so I think it might be sufficient for your use case (it's also uses a `seq[uint32]` instead of `seq[uint8]`, so the operations should be more efficient). While it currently has no support for indexing bytes, that could easily be added.

Regarding your implementation: it's pretty inefficient. For example, `insert` shifts all elements, making it O(n). `seq`s can also be preallocated (since you know the resulting length, or at least an upper bound, beforehand, avoiding reallocations.

Overall, I don't think this should be added to the standard library (I also don't know of any other language that has something like this in its stdlib, apart from bigints; if you do, feel free to add it to a "Prior Art" section). It could be a 3rd party library though, which would also show if people really need this.

**Comment by archnim** [comment]
> Shouldn't this be implemented as a ByteStream, using the streams API for binary data?

Very intersting Idea !

**Comment by archnim** [comment]
> did you just mean a new stdlib type?

Yes. I thought the word "built-in" designated any type that is included when you install nim, including stdlib types. You know, my native language is French. That was not a programming issue, but a language issue.


>I don't see how Multimedia codecs parsers, cryptographic algorithms, database management systems, and so much more would need a new type that is just a wrapper around seq[byte] with some bitwise operations.

You don't see how predefined  bitwise operations can help to code low-level data processing programs ? In the stdlib, There is a `deque` type, a wrapper around seq[T], just to replace simple operations like `echo arr[0]; arr.delete 0` by `echo arr.popFisrt`. But nobody questions its usefulness (And nobody should).


>the official https://github.com/nim-lang/bigints library already supports bitwise operations and shifting along with conversion

First, The official bigints lib is "not expected to work on 32 bit" according to its own README. Next, there are few things to add to it: not operator, casting the content of any string, byte indexing (I know, all that is not that hard to add); And to finish, we could delete all the types defined in the stdlib, and rely on external libraries; but everyone is ok to say that having them out of the box is very practical.


>(it's also uses a seq[uint32] instead of seq[uint8], so the operations should be more efficient)

Yes, in matter of performance, it's more efficient. But I'm proposing a lib that will allow accessing each byte without having to dissociate it from the others through bitwise ops(The goal of the lib is precisely to avoid that). It's true that we can use uint32 in background, and give to the user, an access to each byte. An important fact is that, bigints hasn't been written precisely for low-level raw data processing, but to handle efficiently NUMBERS. Thus, while we can manage to use it in our case, we cannot expect that it fits completely to what we are doing.


>Regarding your implementation: it's pretty inefficient

My implementation can be modified, or even rewritten from zero. I'm here to learn and to contribute.


>Also, no other collection has a custom operator like @:, I think that would only be confusing.

It can be removed. My own implementation of the concept is not what matters the most.


>I also don't know of any other language that has something like this in its stdlib

It doesn't matter :-) If it's useful we can implement it.

**Comment by mratsim** [comment]
> Multimedia codecs parsers
use mmap, no way they put those 50GB  data in RAM.

> cryptographic algorithms
cannot use heap allocated memory in 80% of the cases.

> database management systems
Use temporary strings for raw queries before they are parsed and compiled in a series of instructions internal to the DB chosen and so not under Nim control.

The main use-case I see for that is for serialization/deserialization and transports which don't need xor/and/or and are better served by streams as @Clonkk mentioned.

**Comment by archnim** [comment]
@mratsim we can't predict in advance all the operations needed in all the possible use cases.

Since everyone doubts of the usefulness of my idea, I will keep it as an external lib. But I still need your advices to make it better and more performant. 

Thanks to you all for your patient responses.

I'm one of the ten most Nim-enthusiastic people in the entire universe.

**Comment by konsumlamm** [comment]
> You don't see how predefined bitwise operations can help to code low-level data processing programs ? In the stdlib, There is a `deque` type, a wrapper around seq[T], just to replace simple operations like `echo arr[0]; arr.delete 0` by `echo arr.popFisrt`. But nobody questions its usefulness (And nobody should).

I don't see how a new module with a new type helps there. `std/deques` does not implement `.popFirst()` as `.delete(0)`, it uses an implementation that takes (amortized) O(1) instead of O(n). If it did implement `.popFirst()` as `.delete(0)`, it would indeed be quite useless (in the sense that it would be better to just add deque procs to `std/sequtils` rather than adding a new type + module).

> First, The official bigints lib is "not expected to work on 32 bit" according to its own README.

Yes, I assume this is fixed, but I can't be sure, since noone seems to have a 32 bit CPU for testing.

> It doesn't matter :-) If it's useful we can implement it.

My point is that I don't think it's useful enough to be added to the stdlib. The stdlib should contain stuff that is commonly used and not everything that may occasionally be useful.

**Comment by archnim** [comment]
Well understood. Thank you very much.

**Comment by konsumlamm** [comment]
> Please do you have any advice to make my code more performant ?

First, I'd recommend using [newSeq](https://nim-lang.github.io/Nim/system.html#newSeq%2Cseq%5BT%5D%2CNatural) or [newSeqOfCap](https://nim-lang.github.io/Nim/system.html#newSeqOfCap,Natural) when you know the number of elements needed beforehand. You can also use [setLen](https://nim-lang.github.io/Nim/system.html#setLen%2Cseq%5BT%5D%2CNatural) to set the length of a `seq` to a new value.

Then, you should avoid calling `insert` and similar operations in a loop, since it takes O(n) time. Instead, try to write the elements to the position they're going to have in the end. Even if that is impossible, `add`ing elements to the end and then `reverse`ing the `seq` is still more efficient.

**Comment by archnim** [comment]
Thanks again @konsumlamm 🙂
