### ISSUE TITLE
Destructuring objects by field names

### ISSUE THREAD

**Issue by Tronic** [nim-lang/RFCs#522]
When `person` is an object,

```
let (name, age) = person
```

would be equivalent to

```
let name = person.name
let age = person.age
```

The shorter unpacking syntax is very frequently used in Javascript (ES6), so it seems useful. Since tuple unpacking is already implemented in Nim but it cannot be used with objects, this would complete the feature using the same syntax but with fields names inferred from variable names.

In contrast to positional destructuring (tuple unpack), this avoids the use of underscores to omit fields not needed, but most importantly avoids problems whenever fields are changed. Positional unpacking is error prone and has big maintenance burden if fields are ever changed.

**Comment by Zectbumo** [comment]
If we are remapping then would it be more appropriate to use braces?
```nim
let {name: nameVar, age: ageVar} = person
```
Might as well take the rest of Javascript and do defaults. This may play well with options to set defaults for absent values.

```nim
let {name: nameVar, age: ageVar = 18} = person
```

**Comment by metagn** [comment]
The problem is that braces aren't really used for object construction in Nim.

Also absent values aren't really there either. `Option[T]` is a library type that isn't standard and shouldn't receive special behavior in the language. There are fields in inaccessible object variant case branches but those having default values doesn't really make sense.

**Comment by ZoomRmc** [comment]
> Shouldn't this go in https://github.com/nim-lang/RFCs? Also an alternative could be
> 
> ```nim
> let (name: nameVar, age: ageVar) = person
> ```
> 
> which also works for named tuples

This doesn't look right as it swaps the directionality of the assignment for no good reason.

In my opinion, less foreign approach is to reuse tuple destructuring and provide some sugar for listing object fields on the right side.

```nim
let (a, b, c) = with object: (fieldA, fieldC, fieldZ)
let (a, b, c) = object{fieldA, fieldC, fieldZ}
```

If anyone objects this is too long and wants `let (name, age) = person`, I'll say it's just a sign `person` should have been a tuple from the very start. If one truly needs this syntax, write an object->tuple converter and use it.

**Comment by metagn** [comment]
I don't really even see how variable destructuring is useful for objects. The difference with tuples is that tuples are a quick way to "pack" values together to unpack later, so it's important to make them as seamless as possible. With objects you can't even assign the fields to variables half the time because the fields in the object might be mutated. And it's not really hard to do `let (a, b, c) = (obj.a, obj.b, obj.c)`.

The reason for `name:` etc is that it allows more precision and clarity about exactly which fields the variables correspond to rather than depending on just the order that they are written in. In fact they would elide the need to maintain a specific order if you use named tuples. In JS this is only possible with objects and hence JS needs an object deconstruction syntax.

> it swaps the directionality of the assignment for no good reason.

I don't know what to tell you, this is how destructuring works in any popular language that has it, it mirrors named tuple construction syntax. Otherwise you might as well do `let (a, b) = (obj.a, obj.b)` but it's not like we construct objects by doing `(obj.a, obj.b) = (1, 2)`.

**Comment by ZoomRmc** [comment]
> I don't know what to tell you, this is how destructuring works in any popular language that has it, it mirrors named tuple construction syntax.

Doesn't mean it's good. Using identical syntax for construction and destructuring with assignments going in opposite directions is just not a great idea.

> Otherwise you might as well do let (a, b) = (obj.a, obj.b)

That was basically my point.

**Comment by Araq** [comment]
The proposal as written initially is hereby rejected. But feel free to write an updated version of this RFC that fits Nim.
