### ISSUE TITLE
syntax request: `from std/[foo1,foo2] import nil` ; `from "." / [foo1,foo2] import bar1, bar2, bar3`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#76]
## proposal 1
accept this syntax:
```nim
from std/[foo1,foo2] import nil # equivalent to: from std/foo1 import nil; from std/foo2 import nil; 
from "." / [foo1,foo2] import nil # ditto
```

## proposal 2 
furthermore, also accept this syntax
```nim
from "." / [foo1,foo2] import bar1, bar2, bar3
```
with meaning: 
find each symbol bar1,bar2,bar3 somewhere in import list
The semantics are clear:
CT error if one of these symbols can't be found in import list
no error if a symbol is found in more than 1 module in import list (the usual overloading rules shall apply)

## benefits
* more concise syntax
* in particular, proposal 1 promotes better code for users of that new feature: less symbol pollution (since it requires fully qualified names) compared to `import std/[foo1,foo2]`

**Comment by awr1** [comment]
I think deciding to use fully qualified imports is a matter of personal style rather than something that should be outright discouraged. I prefer to just use `import` too, but sometimes I need to more careful about avoiding name collisions. I like the 2nd proposal too.

Why the `"." /` syntax? Since we can import multiple modules in the same directory with `import x, y, z`, should not `from a, b, c import nil` suffice?

**Comment by timotheecour** [comment]
> Why the "." / syntax?

that RFC doesn't mandate using `"."/`, it's an orthogonal issue.
The reason I used it here is because `import foo` is ambiguous: it can either import `foo.nim` in path or foo in `currentModule.parentDir/foo.nim`
