### ISSUE TITLE
should `static T` be removed from the language?

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#81]
I actually really like `static T` in Nim, IMO it's cleaner than the way C++,D do this, so I'm skeptical but opening this as a centralized place to discuss this since @araq mentioned the following:

https://github.com/nim-lang/Nim/pull/10080#issuecomment-449656127
> static T needs to be removed from the language IMHO. Just allow to pass integer values as type parameters turning the value N into range[0..N-1] would allow almost the same patterns without this never ending clusterfuck of bugs, edge cases and downright unspecified behaviour.

* how would this work without `static T` ? ie, what would we replace this with?
```nim
macro foo(a: int, b: static int): untyped # a becomes NimNode, not b
```

## links
* indeed, there are lots of issues with `static T`: see https://github.com/nim-lang/Nim/labels/Static%5BT%5D
* eg, https://github.com/nim-lang/Nim/issues/10074 should `proc foo[N](dims: array[N, int])` be illegal?
* https://github.com/nim-lang/Nim/issues/10073 can't build a tuple with `static int` element

## note: seems impossible to replace with generic param
in D and C++, `static T` would be done via a generic param; here's the relevant section in D: https://dlang.org/spec/template.html#template_value_parameter

```d
void fun(int b)(int a){  static if(b==1){  writeln(a); } }
```
I'm not even sure if it's possible to have a `static T` of generic type in D, eg, I don't know how to write this in D:
```nim
proc fun1(a: int, b: static int) # ok in D
proc fun2[T](a: int, b: static T) # no idea how to do it in D
```
furthermore, in Nim, Nim generics are rather limited so using D's strategy for `static T` would cripple the feature due to:
* lack of default values for generics in Nim
* lack of partial template instantiation

I'd suggest instead of removing the feature from the language, maybe reconsider its implementation

~~## proposal: implement rewriting as `static => hidden const variable`
Maybe a `static` param can be internally removed from parameter list (both from proc param as well as from generic param) and turned into a hidden `const` variable in that proc scope~~
EDIT : see proposal here: https://github.com/nim-lang/Nim/issues/10085#issuecomment-449839318

**Comment by andreaferretti** [comment]
Back to work, let me explain my use case in some more detail. My main use case for `static[T]` is to attach arbitrary metadata to a type. The idea is to use a generic where the generic parameter is not actually used, but only serves as a marker. Usually this technique is called a "phantom type". Since in Nim any value of a typen `T` can turn into a `static[T]` type, I can store essentially anything into a phantom type.

To make this more concrete, an example can be vectors of known dimension, which is statically tracked:

```nim
type Vector[N: static[int]] = # implementation follows
# A simplistic example can be
# type Vector[N: static[int]] = distinct seq[float]
# or one can use arrays, pointers, not really important
```

The number `N` does not appear explicitly, but can be used to enforce contraints

```nim
# only vectors of the same size can be added together
proc `+`[N: static[int]](v, w: Vector[N]): Vector[N] = ...
```

to use the compiler to compute dimensions

```nim
# only vectors of the same size can be added together
proc concat[M, N: static[int]](v: Vector[M], w: Vector[N]): Vector[M+N] = ...
```

or even to get a constant to use when needed:

```nim
# here we make use of N
proc avg[N: static[int]](v: Vector[N]): float = sum(v) / N.float
```

Another example can be working with integers modulo a fixed number N

```nim
Back to work, let me explain my use case in some more detail. My main use case for `static[T]` is to attach arbitrary metadata to a type. The idea is to use a generic where the generic parameter is not actually used, but only serves as a marker. Usually this technique is called a "phantom type". Since in Nim any value of a typen `T` can turn into a `static[T]` type, I can store essentially anything into a phantom type.

To make this more concrete, an example can be vectors of known dimension, which is statically tracked:

```nim
type Vector[N: static[int]] = # implementation follows
# A simplistic example can be
# type Vector[N: static[int]] = distinct seq[float]
# or one can use arrays, pointers, not really important
```

The number `N` does not appear explicitly, but can be used to enforce contraints

```nim
# only vectors of the same size can be added together
proc `+`[N: static[int]](v, w: Vector[N]): Vector[N] = ...
```

to use the compiler to compute dimensions

```nim
# only vectors of the same size can be added together
proc concat[M, N: static[int]](v: Vector[M], w: Vector[N]): Vector[M+N] = ...
```

or even to get a constant to use when needed:

```nim
proc avg[N: static[int]](v: Vector[N]): float = sum(v) / N.float
```

Another example can be using this technique to make a type for integers modulo a fixed N:

```nim
type Modulo[N: static[int]] = distinct int
```

As above, this can be use to enforce constraints and to use N as a constant:


```nim
proc `+`[N: static[int]](a, b: Modulo[N]): Modulo[N] = Modulo[N]((a.int + b.int) mod N)
```

or even to get specialized implementations for certain values of N:

```nim
proc `+`[N: static[int]](a, b: Modulo[N]): Modulo[N] =
  when N == 256:
    # maybe here we use some specialized implementation with bitshifts
```

In all these examples, I have been using `static[int]`, but there is no need to restrict to that. For instance, one can generalize the `Modulo[N]` example to all these cases where one has the concept of division with remainder (Euclidean rings). Integers are an example, but polynomials over a field are another one. So one can do something like `Modulo[F]`, where `F` is a polynomial.

As it turns out, integers modulo a prime `P` are a field (this means that one can perform division as well as addition, subtraction and multiplication). This allows us to perform division with remainder for polynomials with coefficients in `Modulo[P]`. If `F` is a (statically known) polynomial, having coefficients in `Modulo[P]`, and if `F` is irreducible (again, we can check this at compile time), we can form another field `Modulo[F]`. This is how finite fields are constructed.

If [this bug](https://github.com/nim-lang/Nim/issues/7209) was fixed, I could have a generic implementation of `Modulo`, and use it both for integers and for polynomials, layering it twice!

In emmy, I have a temporary workaround, where I use a macro that takes a `static[int]` N as an input and generates a type for a finite field of size N, provided N is a prime power. It does so by writing `N = P^k` for some prime P, then finding an irreducible polynomial of degree k over the integers modulo P and performing the above construction. All of this works at compile time [today](https://github.com/unicredit/emmy/blob/master/emmy/finite_fields.nim#L18-L35), which is quite nice:

```nim
template makeFiniteField(N: int): untyped =
  when isPrimePower(N):
    const
      P = findPrimePower(N).p
      k = findPrimePower(N).k

    type
      Base = Modulo[P]
      PBase = Polynomial[Base]
      FF = distinct Polynomial[Base]

    let p = generateIrreduciblePolynomial(P, k)

    proc `+`(a, b: FF): FF =
      FF((PBase(a) + PBase(b)) mod p)

    proc `-`(a, b: FF): FF =
      FF((PBase(a) + PBase(b)) mod p)

    # more operations here

macro finiteField*(n: static int, typeName: untyped): untyped =
  result = newStmtList(getAst(makeFiniteField(n)))
  let typeSymbol = result[0][0][1][1][2][0]
  let exported = quote do:
    type `typeName` = `typeSymbol`
  result.add(exported)

# usage
finiteField(8, FF8)
# Here FF8 is a generated type for the finite field with 8 elements
```

So macros taking `static[T]` can be used to generate specialized code using that static value, and as such kind of replace the usage of `static[T]` in generics as a phantom type, but in a less intuitive and convenient way (but they are more robust today)

**Comment by andreaferretti** [comment]
@Araq

> I meant overloading by static T, especially:

This feature is used today in neo: if you import  `neo/static` (this is opt-in), you get overloads to build vectors and matrices of statically known dimensions, which can be freely mixed with dynamic ones. If you call, say `zeros(5)` you get a static vector, while if you call `static(x)` where `x` is a variable with value `5`, you get a dynamic one

**Comment by zah** [comment]
> We agree on that but why isn't it static array[3, static int]? Can static be nested or not?

Well, indeed. If we consider that accessing a slot of a static array is another static value, it looks like the type must be `static array[3, static int]`, but I don't think this is necessary because the evaluation engine needs to apply one operation at a time. It will notice that the array indexing operator:

1) is being invoked over a static value
2) doesn't have side-effects
3) returns `int`, which will be automatically raised to `static int` by the evaluation engine.

This line of thinking sounds a bit confusing for the array type in particular, but it's easy to see how it works correctly for user-defined types and operators.

Otherwise, my previous answer attempted to explain how the signature of the array type determines how the instantiations will look like.

> Secondly, these annotations can do harm for macros.getType.

`tyVar` is already skipped by `getType`, so the same treatment can be applied to `tyStatic` and all the other new modifier types (`tyLent`, `tySink`, etc). One can argue that skipping these types destroys a bit of useful information that can be exploited in macros, so I see two reasonable policies that can apply to all modifier types:

1) Skip them in `getType` and introduce additional magics such as `isLValue`, `isRValue`, `isStatic`, etc. that can be invoked over the macro parameters.

2) Add an optional `skip: set[NimTypeKind]` parameter to `getType` with a default value set to `ntyAllModifiers`. The user will then be able to decide when to exploit the additional information and which modifiers are of interest.

> 4 is of type int so it could be an ambiguity error or call the int variant instead.

As pointed out earlier by @cooldome, any literal is really a type on its own and it can be implicitly converted to a large number of concrete types, one of which is `static int`. And as I said earlier, `static int` is a more specific type than `int` and this justifies having the overload resolution preference (*more specific* here has the usual interpretation based on the fact that every `static int` value can be considered an `int` value, but not vice versa).

**Comment by Araq** [comment]
> This line of thinking sounds a bit confusing for the array type in particular, but it's easy to see how it works correctly for user-defined types and operators.

The implementation "works" by constructing the ``static T`` variant lazily, on demand. I don't think that's what a type system is about. In most type systems expressions have a single type that doesn't involve guesswork during the signature matching process.

**Comment by zah** [comment]
> The implementation "works" by constructing the static T variant lazily, on demand. I don't think that's what a type system is about. In most type systems expressions have a single type that doesn't involve guesswork during the signature matching process.

As usual, things are not very different for `var`. There is no type such as `var array[4, var int]` and the reasoning followed by the compiler is somewhat similar.

> Nevertheless I consider this dispute settled, static T will stay and hopefully we'll be able to improve its spec and implementation.

Well, I proposed one specific change to the spec in this discussion. I hope I'll get some feedback from you and the community before moving on: 

**Proposed reform:** 

1) `static Foo` in macros is typed as a `NimNode` (with some caveats, see point 3). 
2) The AST tree matches precisely what was written at the call-site
3) There is a new magic called `staticValue` (which is similar to `getType`) that returns the well-typed static value the input expression evaluates to. This will take into account the `static T` type of the parameter and will be resolved to the same type.

The same treatment should be applied to `typedesc` parameters to reach full consistency (`staticValue` plays quite a similar role to `getType`).

**Rationale:** 

It's more consistent/beneficial if all macro parameters are always AST. This allows you to more easily insert them in the produced AST results and allows you to inspect the precise syntax used at the call-site.

**Comment by Araq** [comment]
> As usual, things are not very different for var. There is no type such as var array[4, var int] and the reasoning followed by the compiler is somewhat similar.

What we should do here IMO is embraces the "overloading by AST" idea, ``var T`` is about locations like ``someVar.pathExpression[here]`` , ``static T`` is about ``nk*Lit here``. Neither is about "eval it now and see if it works out..."

> Proposed reform:

I like it very much.

**Comment by zah** [comment]
> static T is about nk*Lit here

You often make this suggestion and I find it quite inappropriate. Most often than not, the static values are the result of some computation such as `takesStaticInt(binom(5, 3))`, they are not literals.

**Comment by Araq** [comment]
``binom(5, 3)`` should be evaluated to a literal, it's a ``.noSideEffect`` proc that takes compile-time values. You made this suggestion too, to evaluate it unconditionally in the sem'check before overloading resolution.

**Comment by zah** [comment]
This conflicts with another goal listed in my new proposal for the semantics of static params in macros:

> The AST tree matches precisely what was written at the call-site

I consider this the only reasonable justifications for changing the current semantics.
