### ISSUE TITLE
[RFC] type mismatch error message improvement

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/RFCs#87]
- [ ] The following would be clearer and more concise; especially useful when lots of overloads are shown:

```
test.nim(883, 12) Error: type mismatch: got <Stream, TaintedString>
but expected one of:
proc readLine(f: File; line: var TaintedString): bool
  first type mismatch at position: 1
  required type: File
  but expression 'outp' is of type: Stream
proc readLine(f: File): TaintedString
  first type mismatch at position: 1
  required type: File
  but expression 'outp' is of type: Stream

expression: readLine(outp, line)
      if outp.readLine(line):
```
=>
```
test.nim(883, 12) {if outp.readLine(line):} Error: type mismatch: got <Stream, TaintedString> in expression: readLine(outp, line); candidates:
  proc readLine(f: File {Stream}; line: var TaintedString): bool
  proc readLine(f: File {Stream}): TaintedString
```

**EDIT**
- [ ] furthermore, we should show fully qualified types instead of types, to make it easier to find where symbols are defined and remove ambiguities, eg in case Stream is defined in multiple modules:
```
  proc readLine(f: File {Stream}; line: var TaintedString): bool
=>
  proc readLine(f: mod1.File {mod2.Stream}; line: var mod3.TaintedString): bool
```

**EDIT** the overloads should also show the module + file where they came from (not obvious in complex cases)

**Comment by EriKWDev** [comment]
Made some Mockups in #323. Pasting one of them here with type mismatches for thoughts. Perhaps a bit verbose and I have no idea about feadability, but arrows and colors ftw! And Rust has managed to do it similarly so Nim could too! 

## Many type mismatches
file `pr.nim`
```nim
let stringValue = "Hmm"
stringValue.add(10)
```
### Real vs. Mockup
![image](https://user-images.githubusercontent.com/19771356/152688828-98d826d7-6713-4492-b560-63ead03b7e52.png)
![image](https://user-images.githubusercontent.com/19771356/152688978-cc2cc5b1-bf49-41a7-9b36-f87fac231ff6.png)

**Comment by Araq** [comment]
Colors can be hard to read if the contrast with the background isn't good enough. And you don't know the background color (though maybe you could query it?). Instead of colors, make the error messages less verbose and add a link to a HTML page that explains more.

Good error messages" are subjective, not everybody appreciates the idea that the programmer uses a terminal from 1970 lacking a direct view into the source code so that the compiler has to output the source code side-by-side with the error message.

**Comment by haxscramper** [comment]
The point of annotations like these is not to provide help for a programmer that "uses a terminal from 1970 lacking a direct view into the source code" but to show important context in one place, so users won't have to reach into three separate locations (their editor, the HTML page with more explanation, and the original message of the error).

**Comment by Araq** [comment]
Well since the error message should "pop up" in the editor there is no point in repeating the source code line.

**Comment by Clonkk** [comment]
> Good error messages are subjective, not everybody appreciates the idea that the programmer uses a terminal from 1970 lacking a direct view into the source code so that the compiler has to output the source code side-by-side with the error message.

> Well since the error message should "pop up" in the editor there is no point in repeating the source code line.

I don't understand why the two should be in opposition. There is no reason why the output / formatting of either the LSP server or nimsuggest (which is what your IDE receive information from) should be identical to the formatting of the console stdout output.

Why can't we have good stdout error message in the console AND good formatting in your IDE for those who don't like CLI.

**Comment by Vindaar** [comment]
> Edit: okay, apparently this is not possible with the current implementation so disregard previous point

Even if that may be the case, that is not a good reason to not provide said feature. It only means the implementation might be more work (pretty sure @haxscramper has invested huge amounts of time improving the error message handling in the compiler somewhere......... :face_exhaling: ).

Pure CLI based error messages are still extremely important, imo. First of all there's just plenty of people that use and will continue to use emacs / vim and likely compile their code in their terminal and second even if you're not that kind of person: what happens if you have to ssh into some machine and fix some piece of code there? May not happen to you, but it certainly happens a lot in academia when you're once again asked to fix someone's code running on some computer in some lab. Best programming practices are unfortunately not the norm everywhere.

**Comment by haxscramper** [comment]
Playground also does not have support for any advanced IDE features, but I assume a lot of people either do scratch tests there, or maybe even try out the language for the first time (in that case quality of error messages quite important, it might be a main deciding factor).

**Comment by SolitudeSF** [comment]
> Colors can be hard to read if the contrast with the background isn't good enough. And you don't know the background color (though maybe you could query it?).

Thats why all important info that you will actively read is colorless and colored segments are just visual cues.
This is the most random argument i've seen here.

**Comment by haxscramper** [comment]
Also `--colors=off` is a thing as well

**Comment by Araq** [comment]
> Thats why all important info that you will actively read is colorless and colored segments are just visual cues.

That's not what the example does, a significant part of the error was in yellow...

**Comment by haxscramper** [comment]
Visual cues - underline, error *explanation* is colored. The error itself (type mismatch) and procedure signatures are colorless. We can start debating what is the important part here, or whether we can color cues or important parts, and so on, but this is *so* besides the point, than I don't think it will bring any value to discussion.

**Comment by Araq** [comment]
There is indeed no value in this discussion. I give up and accept I'm the only one left who doesn't like clang's / Rust's / Elm's error messages.

PRs are accepted.

**Comment by EriKWDev** [comment]
I'm trying out the red/green in overloads to show what matches and what doesn't. Don't know if it's as intuitive as one might first think..

![image](https://user-images.githubusercontent.com/19771356/153067098-507e2b43-904f-49cf-ab87-239d4a67dcb4.png)
